### ISSUE TITLE
Allow word document settings customization

### ISSUE THREAD

**Issue by kevinsdooapp** [opensagres/xdocreport#103]
Hi,

I need to set a setting to update the table of content when the document is opened.

This field is located in word/settings part.
```
<w:updateFields w:val="1"/>
```
Is there an existing way to add this field to the word/settings part and/or set its value?

Thank you in advance.

Kévin

**Comment by angelozerr** [comment]
This feature doesn't exists, but you can add your own preprocessor like https://github.com/opensagres/xdocreport/tree/master/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/dom

**Comment by kevinsdooapp** [comment]
Ok thank you!
