### ISSUE TITLE
BigDecimal fields with scale set are not merged with scale

### ISSUE THREAD

**Issue by radufabian** [opensagres/xdocreport#106]
Hi,

I have a merge field in Word 2010 document template which is set from Java as a BigDecimal with scale set to two. After running Java xdocreport with version 1.0.5 the resulted Word doc doe snot contain on that field value the number with scale. 
Example: AMOUNT = 100 and BidDecimal has scale = 2. If displaying this field in Java is 100.00
but in resulted word document the field is still 100 and not 100.00

Thank you, best,
Radu Fabian

**Comment by angelozerr** [comment]
It's a problem with Velocity or Freemarker. I suggest you that you read doc to know how to format BigDecimal.

**Comment by radufabian** [comment]
By using Freemarker formater like ?string["#,###,##0.00"] is working.
Anyway in case the Freemarker formater is not specified then the scale should apply.
Thank you for help
