### ISSUE TITLE
No blank lines on ODT->PDF with itext5

### ISSUE THREAD

**Issue by raphaelazzolini** [opensagres/xdocreport#114]
I was trying to convert an ODT file with blank lines between paragraphs to PDF using the itext5 converter, but these blank lines were not present in the PDF file.
I was able to fix this by changing the postProcessEmptyParagraph() method in StylableParagraph class, inserting _Chunk.NEWLINE_ instead of _new Chunk( ODFUtils.TAB_STR )_ when the paragraph is empty.
I commit this change in my fork repository and I can make a pull request if you like.

**Comment by angelozerr** [comment]
> I commit this change in my fork repository and I can make a pull request if you like.

@raphaelazzolini it should be reaaly cool, thanks!

**Comment by raphaelazzolini** [comment]
@angelozerr I made the pull request #117 for this issue.
