### ISSUE TITLE
Escape of element names with XML datasource

### ISSUE THREAD

**Issue by AndreaGiovannini** [opensagres/xdocreport#127]
#Hi,
I have a problem with XML data-source when the name of the elements include the - character: i'm using FreeMarker and it raises syntax error even if I escape names in the template. This is a screen-shot of my docx template where I reference the element <first-name> in a mergefield:

![image](https://cloud.githubusercontent.com/assets/18442889/14494501/6dbde7a0-018b-11e6-9949-dadcc1887a2b.png)

escaping `first-name` with `first\-name`.
This is the Java code I use to produce the output:

![image](https://cloud.githubusercontent.com/assets/18442889/14494859/3e3e2f4c-018d-11e6-9a75-66f5827bf9d6.png)

I get this error

`Exception in thread "main" freemarker.core.ParseException: Parsing error in template "fr.opensagres.xdocreport.document.docx.DocxReport@227c808d!word/document.xml" in line 4, column 186:
Lexical error: encountered "\\" (92), after "\\".
	at freemarker.core.TokenMgrError.toParseException(TokenMgrError.java:233)
	at freemarker.template.Template.<init>(Template.java:199)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:419)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:330)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:205)
	at freemarker.template.Configuration.getTemplate(Configuration.java:740)
`

How can I escape properly XML element names in the template?
Thank you.

Andrea

**Comment by angelozerr** [comment]
Never done that, perhaps there is a bug but no time to study it. 

> escaping `first-name` with `first\-name`

Why do you do that?

**Comment by AndreaGiovannini** [comment]
The XML comes from a legacy application with - characters in element names so I have to handle them.
I'm escaping - with \- as specified in [http://freemarker.org/docs/app_faq.html#faq_strange_variable_name](http://freemarker.org/docs/app_faq.html#faq_strange_variable_name) but probably the error comes from a non updated Freemarker jar: I'm double-checking with the latest Freemarker jar, I'll let you know asap if it solves the issue.

**Comment by angelozerr** [comment]
I'm afraid that problem comes from XDocReport which doesn't escape this XML. I suggest you to unzip your docx and see the word/document.xml to see how word excape your field.

**Comment by AndreaGiovannini** [comment]
Thank you Angelo: Word adds a second \ in the merge-field
...
<w:fldSimple w:instr=" MERGEFIELD  ${doc.first\\-name}  \* MERGEFORMAT ">
...

I tried with Freemarker 2.3.24 (the latest version available) and got the same error.

If I write Freemarker directives in the document, without using merge-fields, then escaping works correctly (with Freemarker 2.3.24).
Since I don't want to use merge-fields then we can close the issue.

Thank you for XDocReport and for your feedback!

Andrea

**Comment by angelozerr** [comment]
@AndreaGiovannini if you don't use mergefield you will have some problem because sometimes MS word split your Freemarker directive in several XML elements.
