### ISSUE TITLE
Docx to PDF converter font problem

### ISSUE THREAD

**Issue by attilakiss87** [opensagres/xdocreport#129]
I have created a project which uses xdocreport to save the output file to pdf. It works fine, when I run it in Eclipse on Windows, but when I try to do the same on Ubuntu with Tomcat, the output file does not contain the original font. I have created a template .docx file in Word  and I have installed an Ubuntu specific font on Windows, so I can save the template file with this font, which is part of the Ubuntu system, so the software could use it when it runs on Ubuntu. Except it doesn't. The output file has different font then the template, and I do not know why. The bigger problem is that the output font does not contain letters with accents(like 'ő', 'ű') and characters like these are removed from the text.
Any idea what is happening?
Thanks, Attila

**Comment by pensionarchitects-ben** [comment]
The problem probably is that XDocReport can't autorecognize fonts. But luckily with the following code you can add a font. The variable fontLibrary is a string containing the location where the font is stored

```
DocumentKind from = DocumentKind.valueOf("DOCX");
ConverterTypeTo to = ConverterTypeTo.valueOf("PDF");
Options options = Options.getFrom(from).to(to);

PdfOptions pdfOptions = PdfOptions.create();
pdfOptions.fontProvider(new IFontProvider() {

	@Override
	public Font getFont(String familyName, String encoding, float size, int style, Color color) {
	try {
		if (familyName.equalsIgnoreCase("CALIBRI")) {
			BaseFont baseFont =
				    BaseFont.createFont(fontLibrary + "CALIBRI.TTF", encoding, BaseFont.EMBEDDED);
			return new Font(baseFont, size, style, color);

		} else if (familyName.equalsIgnoreCase("CAMBRIA")) {
			BaseFont baseFont =
					BaseFont.createFont(fontLibrary + "CAMBRIA.TTF", encoding, BaseFont.EMBEDDED);
			return new Font(baseFont, size, style, color);
		}
	} catch (Exception e) {
		throw new RuntimeException(e);
	}

	return FontFactory.getFont(familyName, encoding, size, style, color);
	}
});
options.subOptions(pdfOptions);
IConverter converter = ConverterRegistry.getRegistry().getConverter(options);
try {
	FileInputStream is = new FileInputStream(input);
	try {
		FileOutputStream os = new FileOutputStream(outputFile);
		try {
			converter.convert(is, os, options);
		} finally {
			os.close();
		}
	} finally {
		is.close();
	}
} catch (Exception e) {
	throw new RuntimeException(e);
}

```

**Comment by attilakiss87** [comment]
It is more then perfect, thank you very mutch!

**Comment by peterpeterparker** [comment]
@pensionarchitects-ben thx for the piece of code. I have trouble using it in case of Bold font. How did you manage to embedd both NORMAL and BOLD fonts?

**Comment by pensionarchitects-ben** [comment]
@peterpeterparker If i remember correctly the font style is kept in the variable style. In my Unix environments it can select those because my fonts are a collection of multiple files

- CALIBRI.TTF = normal
- CALIBRIB.TTF = bold
- CALIBRII.TTF = italic
- CALIBRIZ.TTF = bold italic

**Comment by peterpeterparker** [comment]
@pensionarchitects-ben  yep argument style (0 = normal, 1 = bold, etc.), I noticed that but somewhere I should miss something else...thx for the feedback anyway, appreciated!

**Comment by pensionarchitects-ben** [comment]
@peterpeterparker Is the text in bold just in normal or did it disappear?

**Comment by peterpeterparker** [comment]
If I convert a docx containing only normal font like

    Test

the conversion is successful. If I try to convert a docx with bold, like

    **Test**

then the conversion doesn't work and tell me that the resulting PDF/A isn't valid because a fond isn't embedded in the document...super strange ;)

**Comment by pensionarchitects-ben** [comment]
Create a separate issue, post the complete stacktrace I will try to check it later. And add the complete font files (if possible)

**Comment by peterpeterparker** [comment]
@pensionarchitects-ben thx a lot! as you see I opened https://github.com/opensagres/xdocreport/issues/228

**Comment by inem88** [comment]
ATTENTION! In this example probably very large memory leak on version 2.0.1 from maven!
I try use it for ODT -> PDF and it's get over 400Mb additional on every file (one page document).
I solve it by use cache font like this:
```
    private static PdfOptions pdfOptions = PdfOptions.create();
    pdfOptions.fontProvider(new IFontProvider() {
        private static Object cacheSync = new Object();
            private static Map<String, Font> cache = new HashMap();
                @Override
                public Font getFont(String familyName, String encoding, float size, int style, Color color) {
                    try {
                        String key = familyName+"_"+encoding+"_"+size+"_"+style+"_"+color.toString();
                        if (familyName.equalsIgnoreCase("CALIBRI")) {
                            if(this.cache.get(key)==null) {
                                synchronized (this.cacheSync) {
                                    if(this.cache.get(key)==null) {
                                        BaseFont baseFont = BaseFont.createFont(fontLibrary + "CALIBRI.TTF", encoding, BaseFont.EMBEDDED);
                                        this.cache.put(key, new Font(baseFont, size, style, color));
                                    }
                                }
                        }
                        return this.cache.get(key);
                    }
                } catch (Exception e) {
                throw new RuntimeException(e);
            }
            return FontFactory.getFont(familyName, encoding, size, style, color);
        }
    });
```
> The problem probably is that XDocReport can't autorecognize fonts. But luckily with the following code you can add a font. The variable fontLibrary is a string containing the location where the font is stored
> 
> ```
> DocumentKind from = DocumentKind.valueOf("DOCX");
> ConverterTypeTo to = ConverterTypeTo.valueOf("PDF");
> Options options = Options.getFrom(from).to(to);
> 
> PdfOptions pdfOptions = PdfOptions.create();
> pdfOptions.fontProvider(new IFontProvider() {
> 
>     @Override
>     public Font getFont(String familyName, String encoding, float size, int style, Color color) {
>     try {
>         if (familyName.equalsIgnoreCase("CALIBRI")) {
>             BaseFont baseFont =
>                     BaseFont.createFont(fontLibrary + "CALIBRI.TTF", encoding, BaseFont.EMBEDDED);
>             return new Font(baseFont, size, style, color);
> 
>         } else if (familyName.equalsIgnoreCase("CAMBRIA")) {
>             BaseFont baseFont =
>                     BaseFont.createFont(fontLibrary + "CAMBRIA.TTF", encoding, BaseFont.EMBEDDED);
>             return new Font(baseFont, size, style, color);
>         }
>     } catch (Exception e) {
>         throw new RuntimeException(e);
>     }
> 
>     return FontFactory.getFont(familyName, encoding, size, style, color);
>     }
> });
> options.subOptions(pdfOptions);
> IConverter converter = ConverterRegistry.getRegistry().getConverter(options);
> try {
>     FileInputStream is = new FileInputStream(input);
>     try {
>         FileOutputStream os = new FileOutputStream(outputFile);
>         try {
>             converter.convert(is, os, options);
>         } finally {
>             os.close();
>         }
>     } finally {
>         is.close();
>     }
> } catch (Exception e) {
>     throw new RuntimeException(e);
> }
> ```

**Comment by cec** [comment]
Hi @pensionarchitects-ben,

I would like to know if the memory leak metioned by @inem88 is still an issue or if it has been fixed.

Thank you :)

**Comment by pensionarchitects-ben** [comment]
@cec 
I have no idea haven't checked this out in years :) I have never stumbled upon this problem but it probably has to do with how you use the code I added. But should be easy enough to check normally.

**Comment by cec** [comment]
@pensionarchitects-ben sorry I understood you were one of the maintainers, my bad, thanks for the quick reply man :)

**Comment by cec** [comment]
Hi @angelozerr ,

I wanted to know if the memory leak mentioned by @inem88 is still an issue or if it has been fixed.

Thank you :)
