### ISSUE TITLE
Is sub reporting possible?

### ISSUE THREAD

**Issue by luisalves00** [opensagres/xdocreport#143]
I have a document that is construct from other documents, which are also available ad-hoc.
The current approach is to merge them with a pdf library, but this will fail if we need to put page numbering. Is there a better way to do this?

**Comment by angelozerr** [comment]
Goal of XDocReport is to provide a simple mean to write report with MS Office or OpenOffice (even if you are not developer you can design a report).

Sub report is complex (to design report) and hard to implement. If you need sub report, you should use  another Report engine like JasperReports, Bird, etc
