### ISSUE TITLE
Old version of Apache POI used in org.apache.poi.xwpf.converter.core

### ISSUE THREAD

**Issue by Gagravarr** [opensagres/xdocreport#146]
The pom file for org.apache.poi.xwpf.converter.core shows it's using Apache POI 3.10. Ideally it should use the most recent release, but if not it needs to use 3.10.1 for a security fix - see http://poi.apache.org/changes.html#3.10.1

**Comment by angelozerr** [comment]
@pascalleclercq could you see this issue please?

**Comment by pascalleclercq** [comment]
Upgraded POI to 3.15-beta2

**Comment by angelozerr** [comment]
Thanks @pascalleclercq !
