### ISSUE TITLE
freemarker wont clear its internal caches - OOM after several thousand runs

### ISSUE THREAD

**Issue by jkleemann** [opensagres/xdocreport#16]
Using this code:
```
InputStream xmlIn = new ByteArrayInputStream(this.getData());
InputStream tmplIn = this.getInputStreamForExternal(getAttribute("template",null));
	            
IXDocReport report = XDocReportRegistry.getRegistry().loadReport( tmplIn, TemplateEngineKind.Freemarker );
IContext context = report.createContext();

// XML input data as source
InputSource projectInputSource = new InputSource( xmlIn );
	            freemarker.ext.dom.NodeModel project = freemarker.ext.dom.NodeModel.parse( projectInputSource );
context.put( "doc", project );
	            
ByteArrayOutputStream out = new ByteArrayOutputStream(320000);
report.process( context, out );

// Unregistering -> Since unclear how input streams will be cached ? 
XDocReportRegistry.getRegistry().clear();
return out.toByteArray();
```
to perform templating. It seems that freemarker code uses cache which will never get cleared. Even under high pressure the cache grows and produces OOM after several thousand iterations. 

Any hints on how to handle this:
a.) using another load mechanism (URL instead of stream) so freemarker can efficiently use caching ?
b.) configuring freemarker cache differently ?
c.) exposing freemarker cache to evtl. clear it actively ?

![docxrep-2015-02-27-3 snapshot _users_jkleemann_snapshots - yourkit java profiler 2013 build 13086 - 64-bit](https://cloud.githubusercontent.com/assets/61286/6416986/9837b9ea-beaa-11e4-989f-2d0291ff5772.png)

**Comment by jkleemann** [comment]
ok, first looking into the code then "complaining"... I fixed it by using a report ID to load a template:


// getAttribute("template",defValue) returns the template URI/URL so its unique
IXDocReport report =XDocReportRegistry.getRegistry().loadReport(tmplIn,getAttribute("template",null),TemplateEngineKind.Freemarker);

**Comment by angelozerr** [comment]
To have a very good performance, you must use `IXDocReportRegistry#loadReport` the first time and `IXDocReportRegistry#getReport` the second time. See https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMain#5._Test_Performance

By default XDocReport uses Freemarker cache. If you don't wantt o use this cache (and not use loadReport/getReport) you can call for instance this loadReport https://github.com/opensagres/xdocreport/blob/master/document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/registry/XDocReportRegistry.java#L284
with cacheReport to false.
