### ISSUE TITLE
Table in loop test Chinese issue

### ISSUE THREAD

**Issue by beijingfan** [opensagres/xdocreport#161]
Hello，
    I use this code to export pdf file，but when I use chinese character to replace table field，These characters are not displayed，Code is as follows：

package fr.opensagres.xdocreport.samples.docxandvelocity;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

import fr.opensagres.xdocreport.converter.ConverterTypeTo;
import fr.opensagres.xdocreport.converter.ConverterTypeVia;
import fr.opensagres.xdocreport.converter.Options;
import fr.opensagres.xdocreport.core.XDocReportException;
import fr.opensagres.xdocreport.document.IXDocReport;
import fr.opensagres.xdocreport.document.registry.XDocReportRegistry;
import fr.opensagres.xdocreport.samples.docxandvelocity.model.Developer;
import fr.opensagres.xdocreport.samples.docxandvelocity.model.Project;
import fr.opensagres.xdocreport.template.IContext;
import fr.opensagres.xdocreport.template.TemplateEngineKind;
import fr.opensagres.xdocreport.template.formatter.FieldsMetadata;

public class DocxProjectWithVelocityList2PDF {

	public static void main(String[] args) {
		try {
			// 1) Load Docx file by filling Velocity template engine and cache
			// it to the registry
			InputStream in = DocxProjectWithVelocityList2PDF.class.getResourceAsStream("DocxProjectWithVelocityList.docx");
			IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Velocity);

			// 2) Create fields metadata to manage lazy loop (#foreach velocity) for table row.
	        FieldsMetadata metadata = report.createFieldsMetadata();
			// Old API 
	        /*
	        metadata.addFieldAsList("developers.Name");
			metadata.addFieldAsList("developers.LastName");
			metadata.addFieldAsList("developers.Mail");
			*/
	        // NEW API
			metadata.load( "developers", Developer.class, true );
			
			// 3) Create context Java model
			IContext context = report.createContext();
			// Register project
			Project project = new Project("XDocReport");
			context.put("project", project);
			// Register developers list
			List<Developer> developers = new ArrayList<Developer>();
			developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));
			developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));
			developers.add(new Developer("中文", "无法显示", "beijing@gmail.com"));
			context.put("developers", developers);
			
			// 4) Generate report by merging Java model with the Docx
			OutputStream out = new FileOutputStream(new File(
					"DocxProjectWithVelocityList_Out.pdf"));
			// report.process(context, out);
			Options options = Options.getTo(ConverterTypeTo.PDF).via(
					ConverterTypeVia.XWPF);
			report.convert(context, options, out);

		} catch (IOException e) {
			e.printStackTrace();
		} catch (XDocReportException e) {
			e.printStackTrace();
		}
	}
}

I also tried mixing in English, but the Chinese still do not show，looking forward to your reply, thank you very much

**Comment by beijingfan** [comment]
This problem has been solved, xdocreport example code has a solution, Unicode Text-like this one can be solved in a similar way, just add the following code in the font reference can be:：

PdfOptions pdfOptions = PdfOptions.create();
			pdfOptions.fontProvider(new IFontProvider() {
				public Font getFont(String familyName, String encoding, float size, int style, Color color) {
					try {
						BaseFont bfChinese = BaseFont.createFont("c:/Windows/Fonts/arialuni.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
						Font fontChinese = new Font(bfChinese, size, style, color);
						if (familyName != null)
							fontChinese.setFamily(familyName);
						return fontChinese;
					} catch (Throwable e) {
						e.printStackTrace();
						// An error occurs, use the default font provider.
						return ITextFontRegistry.getRegistry().getFont(familyName, encoding, size, style, color);
					}
				}
			});
			options.subOptions(pdfOptions);

I tested IT OK

**Comment by angelozerr** [comment]
@beijingfan glad you have found the solution.

I close this issue.
