### ISSUE TITLE
Null template engine

### ISSUE THREAD

**Issue by joseluislopez87** [opensagres/xdocreport#164]
Hello,

I'm trying to deploy an uber-jar of my Maven project that uses Xdocreport to generate a Docx with Velocity template engine.

It's running OK in Eclipse, but when I execute mvn install and java -jar my-uber-jar.jar from CLI, I get the following error:

`Error setting data in context: Null template engine. Set template engine with IXDocReport#setTemplateEngine.`

My pom.xml includes the following dependencies:

```
<dependencies>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.xwpf</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>oro</groupId>
			<artifactId>oro</artifactId>
			<version>2.0.8</version>
		</dependency>
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.6</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.21</version>
		</dependency>
		<dependency>
			<groupId>com.documents4j</groupId>
			<artifactId>documents4j-api</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.documents4j</groupId>
			<artifactId>documents4j-local</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.odt.odfdom</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-scratchpad</artifactId>
			<version>3.12</version>
		</dependency>
		<dependency>
			<groupId>com.artofsolving</groupId>
			<artifactId>jodconverter</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlgraphics</groupId>
			<artifactId>fop</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>itextpdf</artifactId>
			<version>5.3.4</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.2.11</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
```
And packaging section:
```
<build>
		<plugins>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>full.path.main.class.Application</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```
Thanks in advance, regards

**Comment by angelozerr** [comment]
I have never played with "uber-jar", but XDOcReport uses SPI to load template engine, document kind, etc. Check you have https://github.com/opensagres/xdocreport/blob/master/template/fr.opensagres.xdocreport.template.velocity/src/main/resources/META-INF/services/fr.opensagres.xdocreport.template.discovery.ITemplateEngineDiscovery in your JAR

**Comment by joseluislopez87** [comment]
Hi,
Yes, in the generated jar there is the file META-INF/services/fr.opensagres.xdocreport.template.discovery.ITemplateEngineDiscovery and the content is correct (fr.opensagres.xdocreport.template.velocity.discovery.VelocityTemplateEngineDiscovery) - I use Velocity as my template engine.

Thanks, regards

**Comment by angelozerr** [comment]
Your problem is about SPI and uber JAR (never used uber JAR).  Check you have the same files in your JAR like https://github.com/opensagres/xdocreport/tree/master/template/fr.opensagres.xdocreport.template.velocity/src/main/resources an dfor other JARs.

It seems that some people have problem with SPI and uber JAR like https://java.net/jira/browse/TRUEVFS-117

**Comment by joseluislopez87** [comment]
Hello Angelo,

I've checked for all the files and I think I have all dependencies inside my fat jar (screenshots attached), please correct me if I'm missing something or I'm doing something wrong.

I'm getting the same error like http://stackoverflow.com/questions/34763127/xdocreport-generating-file-in-ide-but-not-from-a-jar where the autor solves it moving to Freemaker, but I need to use Velocity.

I never worked with SPI, but all I want is just execute my application from CLI (java -jar myapplication.jar) same way I'm doing in Eclipse (right button in main Application.java > run as > Java application)

Thank you very much for your help, regards

![jar-with-dependencies1](https://cloud.githubusercontent.com/assets/5657386/18780640/cece8400-817e-11e6-9ec5-12e3dfae52e1.JPG)
![jar-with-dependencies2](https://cloud.githubusercontent.com/assets/5657386/18780642/ced23cd0-817e-11e6-8b34-85c8ab71810b.JPG)
![jar-with-dependencies3](https://cloud.githubusercontent.com/assets/5657386/18780641/ced20d8c-817e-11e6-8088-187b4685591a.JPG)
![jar-with-dependencies4](https://cloud.githubusercontent.com/assets/5657386/18780643/ced4ae7a-817e-11e6-99c1-dcdcd9ab571e.JPG)

**Comment by angelozerr** [comment]
Is the content of fr.opensagres.xdocreport.template.discovery.ITemplateEngineDiscovery?

`fr.opensagres.xdocreport.template.velocity.discovery.VelocityTemplateEngineDiscovery`

If it that, I don't know -(

**Comment by joseluislopez87** [comment]
Yes, the content is exactly that.

I've created a repository with minimal code to test the problem: https://github.com/joseluislopez87/testXdocreport

Ready to execute `mvn install` in the root.
The jar generated in the target folder is not running by CLI, but if you import the project in Eclipse and execute `Application.java` file as a Java Application, it runs ok.

Thanks for your help, regards

**Comment by joseluislopez87** [comment]
Hi,

Issue solved. The problem was importing the following dependencies into pom.xml:

- fr.opensagres.xdocreport.document
- fr.opensagres.xdocreport.template

After removing them, the uber-jar works like a charm. I've updated the code in the repo [https://github.com/joseluislopez87/testXdocreport](https://github.com/joseluislopez87/testXdocreport)

Thank you very much @angelozerr for your time and effort, congratulations for the framework and I hope this can be useful to other users.

Regards

**Comment by corvo-berlino** [comment]
Even nearly ten years later: Thank you very much :-)
