### ISSUE TITLE
ServiceLoader issues

### ISSUE THREAD

**Issue by cetra3** [opensagres/xdocreport#17]
Right now dependency of document formats and template engines is handled via `ServiceLoader`.  This is causing issues with plugin discovery in existing java applications since not all jars may be available by the current Thread Context Classloader.

An example of the error I've seen is:
```
fr.opensagres.xdocreport.core.XDocReportException: Impossible to create report for the input stream. The report loader supports only [] files type.
```

I'm wondering if there is a way of manually declaring capabilities available, so that we can explicitly set what converters are available rather than relying on ServiceLoader to determine this for us.  I.e, we can construct the XDocReport class instance and say: *use this document type and this template engine*.

**Comment by angelozerr** [comment]
> This is causing issues with plugin discovery in existing java applications since not all jars may be available by the current Thread Context Classloader.

I don't understand very well? Where do we use current Thread Context Classloader for ServiceLoader?

> I'm wondering if there is a way of manually declaring capabilities available, so that we can explicitly set what converters are available rather than relying on ServiceLoader to determine this for us. I.e, 

Never done that, but you should call directly the implementation of template enfine, document, converter instead of calling interface API.

**Comment by angelozerr** [comment]
None answer, I close this issue.
