### ISSUE TITLE
xdocreport using org.apache namespaces for classes that are not from apache

### ISSUE THREAD

**Issue by JMarkMurphy** [opensagres/xdocreport#174]
It seems to me that it is not the best idea to hijack namespaces from established projects as you can't be sure you will not be causing namespace collisions in the future. I know there is a lot missing from XWPF, but maybe you would be willing to contribute some stuff back to the POI project so you don't have to use our namespace for your own extensions?

jmarkmurphy at apache dot org

**Comment by angelozerr** [comment]
@JMarkMurphy I agree with you. My idea was to give to Apache our converter. But because we use itext for our PDF converter, you were not interested.

If I understand, we must change our package names, is that?

**Comment by JMarkMurphy** [comment]
It is not that we aren't interested. The problem with iText is licensing. It must be compatible with the Apache 2.0 License. iText uses GPL 3.0, and while the GPL folks say that the Apache 2.0 license is compatible with GPL code, it doesn't work the other way around. I'm not real sure what we could do about that.

Otherwise, it probably is best to adjust your package name to reference your organization vs. org.apache.

**Comment by JMarkMurphy** [comment]
One possible option is Apache PDFBox. That is guaranteed to not have licensing issues. I haven't worked with it at all though.

**Comment by angelozerr** [comment]
> One possible option is Apache PDFBox.

I have investigated this idea, but PDFBox doesn't provide a PDF DOM Document like iText, so it's very hard -(

> Otherwise, it probably is best to adjust your package name to reference your organization vs. org.apache.

We should change the package name, but my big problem is that I'm very busy with other projects -(

@pascalleclercq is there any chance that you will find time to do that? Thanks!

**Comment by maxxyme** [comment]
FYI there is currently a fork from the latest version of iText under the LGPL, [LibrePDF/OpenPFD](https://github.com/LibrePDF/OpenPDF).

**Comment by JMarkMurphy** [comment]
I'm not sure that you can fork a GPL project, and just change the license. I believe that is one of the problems that Apache has with GPL. All derivatives must be GPL as well. This is just me talking though. I am not certain on that.

**Comment by evernat** [comment]
@JMarkMurphy 
You said that iText is licensed as GPL 3.0. That's not true.
iText **v2.1.7** is licensed as MPL or at your choice LGPL. You can confirm that in the pom.xml at:
https://repo1.maven.org/maven2/com/lowagie/itext/2.1.7/itext-2.1.7.pom
Is MPL license compatible to Apache license ? 

Note that iText v2.1.7 is not the same as iText v5.x. Starting from v5, the authors of iText has changed the licenses to AGPL (Affero) or Commercial.

**Comment by Gagravarr** [comment]
MPL can be used by Apache Software Foundation projects with some restrictions, http://www.apache.org/legal/resolved.html#category-b details what those are. Non-ASF projects using the Apache License v2 are welcome to do whatever they want! The ASF wants to ensure "no surprises" for users, so has extra restrictions on licenses of dependencies

**Comment by pascalleclercq** [comment]
For the next xdocreport 2.0.x.
I refactored the projects so there won't be any namespace but fr.opensagres.

I will be able to make the release 2.0.0 very soon.

I hope people will migrate ASAP but I can"t remove artifacts from central maven repo.
