### ISSUE TITLE
about Report types: Tabular and its Transpose(Timeseries)

### ISSUE THREAD

**Issue by pablo3p** [opensagres/xdocreport#18]
Hi there,
I was able to create reports using your xDocReports to create column based tabular reports.
But I don't know the syntax to make a report based on the Transpose of this.(this type of report could also be called a Timeseries type of report.
I have attached 2 images to illustrate what I am referring to.

Regards,
P
![salesprofitreports_tabular1](https://cloud.githubusercontent.com/assets/11336298/6623664/8d37c778-c8a1-11e4-96af-9e208c8119b3.png)
![salesprofitreports021](https://cloud.githubusercontent.com/assets/11336298/6623665/8d3aecdc-c8a1-11e4-86b6-476bff9567e9.png)

**Comment by angelozerr** [comment]
@pablo3p I'm sorry I don't understand your need?

Have you read https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainListFieldInTable and https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainListFieldAdvancedTable Perhaps it will help you?

**Comment by pablo3p** [comment]
Hi Angelo,
Thanks for the response.
If you look at the first image that I have in my post.
This first image has the data in columns, you see the headers as column headers(Date,Revenue, Cost, Profit).
This is the tabular report. I was able to easily generate this with xdocreports.

BUT, if you scroll down in the report, you will see another table and it is oriented in a row based way instead of columns.
You see that the column based table has been "Transposed", this it a mathematical term that comes from Matrix math.
A transpose transforms Columns to Rows, or Rows to Columns.
I need to orient the column based table(first image) to the row based table(second image).

Sincerely.

P

**Comment by angelozerr** [comment]
Ok It seems that you wish to manage dynamic Columns.

XDocReport was not designed for that at first, but it's possible by using @before-cell @after-cell like @before-row @after-row https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainListFieldAdvancedTable 

If I remember you can find a sample in the sample docxandfreemarker-*-sample.zip

**Comment by pablo3p** [comment]
Hi,
I looked at your link and cannot find an example with: @before-cell @after-cell.
Also searched the repository and cannot find reference to : @before-cell @after-cell, either.
Can you point me to an example.

Regards,

P

**Comment by angelozerr** [comment]
https://github.com/opensagres/xdocreport.samples/blob/master/samples/fr.opensagres.xdocreport.samples.docxandvelocity/src/fr/opensagres/xdocreport/samples/docxandvelocity/DocxTableWithoutFieldsMetadataWithVelocity.docx

**Comment by pablo3p** [comment]
Hi Angelo,
Thanks really appreciate it.
Thank again.

P

Date: Fri, 13 Mar 2015 15:07:26 -0700

**Comment by pablo3p** [comment]
Hi Angelo,
Thanks for the links.
Really, really appreciate it!
Thanks again!

P

**Comment by angelozerr** [comment]
> Thanks again!

You are welcome, but pay attention with @before-cell/@after-cell. If I remember there are some problems (don't remember which problems), that's why I have not spoken on the wiki.
