### ISSUE TITLE
Chart with xdocreport

### ISSUE THREAD

**Issue by jyotiverma0310** [opensagres/xdocreport#184]
Is there any possible way to create chart using xdocreport?
I am trying to do it using template but not able to figure out how it can be done.

**Comment by angelozerr** [comment]
No it's not possible.

**Comment by jyotiverma0310** [comment]
@angelozerr Okay, Thank you for your quick response.

**Comment by lizeze** [comment]
@jyotiverma0310  Do you have a solution to this problem?
