### ISSUE TITLE
Problem while converting docx in pdf having two columns using XWPF

### ISSUE THREAD

**Issue by jyotiverma0310** [opensagres/xdocreport#189]
I am trying to convert a msword doc in pdf using XWPF. That page have two columns. So when i convert it into pdf then it could not convert correctly somehow. Is there any way to convert doc in pdf that's split in two columns.

I am giving option like below :
options = Options.getFrom(DocumentKind.DOCX).to(ConverterTypeTo.PDF).via(ConverterTypeVia.XWPF);

**Comment by angelozerr** [comment]
> I am trying to convert a msword doc in pdf using XWPF. 

doc or docx? if it's doc, our converter supports only docx and not doc which is binary format.

**Comment by angelozerr** [comment]
So I think it's a bug with the converter. Please attach your docx that you wish to convert and you will try to fix the problem when you will find time

**Comment by jyotiverma0310** [comment]
May be I figured it out, we need to split page in two parts while converting docx to pdf by setting subOptions. I am currently working on it. Hopefully i will able to solve this.
