### ISSUE TITLE
Can't convert odt with tables to PDF

### ISSUE THREAD

**Issue by sukillo** [opensagres/xdocreport#19]
I'm trying to convert an ODT template into PDF using Freemarker. First i fill the template (in another ODT file) from DB then convert it into PDF but always receive the same error in the conversion (java.lang.NoSuchMethodError: org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableTableCell.setRowspan(I)V).
Need any config file for tables? Thanks for help

Code
-----------------------------------------------------------------------------------

try {
			// 1) Load ODT file by filling Velocity template engine and cache
			// it to the registry
			InputStream in = Prueba1.class.getResourceAsStream("pruebaTabla.odt");
			IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Freemarker);

			// 2) Create context Java model
			IContext context = report.createContext();      
            		//Add data into context
            		context.put("numidentidad", numIdentidad);
			context.put("nombre", nombre);
			context.put("apellido1", apellido1);
			context.put("apellido2", apellido2);
			context.put("fechanacimiento", fechaNacimiento);
			context.put("telefonofijo", telefonoFijo);
			context.put("telefonomovil", telefonoMovil);
			context.put("correoelectronico", correoElectronico);
			
			File file = new File("Plantilla2.odt");
			FileOutputStream out = new FileOutputStream(file);
			
			// 3) Generate report by merging Java model with the ODT
			report.process(context, out);			
			FileInputStream inRead = new FileInputStream(file);

			 //4) Load odt with ODFD
			OdfTextDocument document = OdfTextDocument.loadDocument(inRead);
			inRead.close();
			out.close();
			
			// 5) Convert ODFDOM OdfTextDocument 2 PDF with iText
			OutputStream salida = new FileOutputStream(outFile);
			PdfOptions options = PdfOptions.create();
			PdfConverter.getInstance().convert(document, salida, options);
			Desktop.getDesktop().open(outFile);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (XDocReportException e) {
			e.printStackTrace();
		}

**Comment by angelozerr** [comment]
Have you check that you use the same iText version than XDocReport (2.1.7) 

Have you check that you have not several version of iText in your classpath?

**Comment by sukillo** [comment]
Hi angelo, thanks for your answer. Solved the problem. Templates that i received was created with Microsoft Word then saved as odt. I think that is the problem because create the template with Writer and havent problems in conversion. Thank for help!

**Comment by angelozerr** [comment]
Ok cool, thank's for your feedback.
