### ISSUE TITLE
Xdocreport spawns a non-daemon timer thread which prevents application from exiting

### ISSUE THREAD

**Issue by AlainKnaff** [opensagres/xdocreport#194]
Hi,

When getting the registry (using XDocReportRegistry.getRegistry()), xdocreport spawns a timer thread which is not marked as daemon. This thread is apparently never stopped, neither registry.clear(), nor registry.setClearTimeout(1), nor registry.unregisterReport(report) does anything.

At the end of the execution, the presence of this non-daemon thread prevents the application from exiting, and an explicit System.exit(0) is needed.

Thread Timer-0
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)

To prevent such, the thread should be created as a daemon thread (which is possible, even for timers)
https://docs.oracle.com/javase/8/docs/api/java/util/Timer.html#Timer-boolean-

Thanks,

Alain

**Comment by angelozerr** [comment]
@AlainKnaff thanks for your info.

@pascalleclercq could you fix please this issue. Thanks!

**Comment by pascalleclercq** [comment]
Already in dev branch since 199253d405fb0f09dcf99a255624d08e2b545af6 (5 months ago).

Will release 2.0.1 very soon !!!

**Comment by AlexBischof** [comment]
Hi,

i'm currently using 2.0.1 and i think the problem still exists. Here is my code

```
String s = "Briefpapier mit Bankverbindung";
try (InputStream in = new FileInputStream(s + ".docx");
     OutputStream out = new FileOutputStream(s +".pdf")) {

    // 1) Load Docx file by filling Freemarker template engine and cache
    // it to the registry
    XDocReportRegistry registry = XDocReportRegistry.getRegistry();
    IXDocReport report = registry.loadReport(in, Freemarker);

    // 2) Create context Java model
    Person person = new Person();
    person.setFirma("Musternmann GmbH");

    IContext context = report.createContext();
    context.put("person", person);

    // 3) Generate report by merging Java model with the Docx
    Options options = Options.getTo(PDF).via(XWPF);
    report.convert(context, options, out);
} catch (IOException | XDocReportException e) {
    e.printStackTrace();
}
```

**Comment by angelozerr** [comment]
> It works with registry.dispose() but this feels a little bit strange. It is possible to use the Java Closable Interface for this?

Yes you are right. My PR https://github.com/opensagres/xdocreport/commit/ddbb103311490fb52d2bc770d6ee3268ffb3939f should fix your problem since Timer is created only if you call setClearTimeout.
