### ISSUE TITLE
SimpleImageInfo does not support JPEG/Exif format

### ISSUE THREAD

**Issue by Rizen59** [opensagres/xdocreport#20]
Hello everyone,

Some jpeg images are not recognized by the SimpleImageInfo class. Here is a simple test to reproduce the problem:
```
InputStream in = TestClass.class.getResourceAsStream("your-image.jpg");
SimpleImageInfo info = new SimpleImageInfo(in);
System.out.println(info.getMimeType());
```
Here are two different JPEG files format found on google:
A JPEG/JFIF format : http://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg422jfif.jpg
A JPEG/Exif format : http://abbysfloraldesigns.com/wp-content/uploads/2012/11/2004-12-21-071.jpg

In case of the exif image (which is the format used by some digital cameras) an IOException is thrown (message = "Unsupported image type") : this can cause a failure during the report generation.
After some research this format is using an Appn marker that is not seem to be take into account on the algorithm.

Thanks in advance for your feedback.

**Comment by angelozerr** [comment]
Done with https://github.com/opensagres/xdocreport/pull/22
