### ISSUE TITLE
Method POIXMLDocumentPart.getPackageRelationship() used in XWPFStylesDocument class was deprecated in version 3.16

### ISSUE THREAD

**Issue by guilherme737** [opensagres/xdocreport#208]
When trying to convert a docx to pdf bugs error:

`java.lang.NoSuchMethodError: org.apache.poi.POIXMLDocumentPart.getPackageRelationship()Lorg/apache/poi/openxml4j/opc/PackageRelationship;
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.getFontsDocument(XWPFStylesDocument.java:1480) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:191) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:185) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.createStylesDocument(XWPFDocumentVisitor.java:167) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.<init>(XWPFDocumentVisitor.java:160) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.<init>(PdfMapper.java:149) ~[fr.opensagres.poi.xwpf.converter.pdf-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:56) ~[fr.opensagres.poi.xwpf.converter.pdf-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39) ~[fr.opensagres.poi.xwpf.converter.pdf-2.0.0.jar:2.0.0]
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46) ~[fr.opensagres.poi.xwpf.converter.core-2.0.0.jar:2.0.0]
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67) ~[fr.opensagres.xdocreport.converter.docx.xwpf-2.0.0.jar:2.0.0]`

**Comment by angelozerr** [comment]
Perhaps https://github.com/opensagres/xdocreport/pull/206 fix this problem?

**Comment by icode** [comment]
waiting push to maven repo.......

**Comment by icode** [comment]
@angelozerr when publish release to maven repo?

**Comment by angelozerr** [comment]
@pascalleclercq what do you think?

**Comment by icode** [comment]
@pascalleclercq I want down load from repo new version 2.0.1

**Comment by StoneRivers** [comment]
@pascalleclercq @pascalleclercq. Do you have any plan about  publishing the 2.0.1 ?

**Comment by ryanthon** [comment]
Any updates on this? @pascalleclercq

**Comment by joelchrist** [comment]
Any updates on this? Downgrade POI for now?

**Comment by jwhitmarsh** [comment]
Any updates?

**Comment by angelozerr** [comment]
@pascalleclercq ?

**Comment by huygir** [comment]
Did we just give up on this?  Why is no one responding with a plan to publish a fix - it's obviously effecting a lot of users.  Still happening in January 2018!

**Comment by huygir** [comment]
P.S. - usually when a function or feature is deprecated you give users a reasonable amount of time to migrate before dramatically terminating use.  Is there some combination of legacy builds that still work or are we forced to build our own?  clusterfup

**Comment by huygir** [comment]
Backed up to 3.15 - works, not fast but it works

**Comment by angelozerr** [comment]
@pascalleclercq when you will have time, do you think it's possible to create a new release? Thanks!

**Comment by angelozerr** [comment]
> Still happening in January 2018!

Please note that we do XDocReport in our free time. It's hard for us to find time today.

**Comment by Heanthor** [comment]
Has there been any movement on this?

**Comment by khausam** [comment]
I was using:
compile group: 'fr.opensagres.xdocreport', name: 'org.apache.poi.xwpf.converter.xhtml', version: '1.0.6'

I switched to:
compile group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.poi.xwpf.converter.xhtml', version: '2.0.1'

And the problem was resolved. Can anyone confirm whether this is a reasonable and viable upgrade path?

**Comment by marcoxsurf** [comment]
I used this dependecies to fix the problem as suggested by @khausam :
                `<dependency>
		    <groupId>fr.opensagres.xdocreport</groupId>
		    <artifactId>fr.opensagres.poi.xwpf.converter.pdf</artifactId>
		    <version>${xdocreport.version}</version>
		</dependency>
		
		<dependency>
		    <groupId>fr.opensagres.xdocreport</groupId>
		    <artifactId>fr.opensagres.poi.xwpf.converter.xhtml</artifactId>
		    <version>${xdocreport.version}</version>
		</dependency>`

but the pdf output was not as expected

**Comment by dschulten** [comment]
I was using 

	<dependency>
		<groupId>fr.opensagres.xdocreport</groupId>
		<artifactId>org.apache.poi.xwpf.converter.pdf</artifactId>
		<version>1.0.5</version>
	</dependency>

which has a dependency on poi 3.15 and had problems because tika insisted that It needed poi 3.16.

Switched to:

	<dependency>
	    <groupId>fr.opensagres.xdocreport</groupId>
	    <artifactId>fr.opensagres.poi.xwpf.converter.pdf-gae</artifactId>
	    <version>2.0.1</version>
	</dependency>

and had to adjust a few package names, then it worked

**Comment by habean** [comment]
I was using
<dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-scratchpad</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.xdocreport.document</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>org.apache.poi.xwpf.converter.xhtml</artifactId>
            <version>1.0.6</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons.io</groupId>
            <artifactId>commonsIO</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.aspose.words</groupId>
            <artifactId>aspose-words</artifactId>
            <version>15.8.0</version>
        </dependency>
This problem still occurs during the process of use.
java.lang.NoSuchMethodError: org.apache.poi.POIXMLDocumentPart.getPackageRelationship()Lorg/apache/poi/openxml4j/opc/PackageRelationship;
Is there any solution? It seems that the package conflicts.

**Comment by angelozerr** [comment]
2.0.3 has been released. Thanks so much @pascalleclercq !

**Comment by Alension** [comment]
> I was using org.apache.poi poi 3.17 org.apache.poi poi-ooxml 3.17 org.apache.poi poi-scratchpad 3.17 fr.opensagres.xdocreport fr.opensagres.xdocreport.document 2.0.1 fr.opensagres.xdocreport org.apache.poi.xwpf.converter.xhtml 1.0.6 org.apache.commons.io commonsIO 2.5.0 com.aspose.words aspose-words 15.8.0 This problem still occurs during the process of use. java.lang.NoSuchMethodError: org.apache.poi.POIXMLDocumentPart.getPackageRelationship()Lorg/apache/poi/openxml4j/opc/PackageRelationship; Is there any solution? It seems that the package conflicts.


I have the same problem as you. I switch to the following, then it worked
                        <dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
				<version>5.2.2</version>
				<exclusions>
					<exclusion>
						<groupId>org.apache.logging.log4j</groupId>
						<artifactId>log4j-api</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>fr.opensagres.xdocreport</groupId>
				<artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
				<version>2.0.4</version>
			</dependency>
			<dependency>
				<groupId>fr.opensagres.xdocreport</groupId>
				<artifactId>fr.opensagres.poi.xwpf.converter.pdf</artifactId>
				<version>2.0.4</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-to-slf4j</artifactId>
				<version>2.17.2</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>2.17.2</version>
			</dependency>
                        <dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>2.11.0</version>
			</dependency>
