### ISSUE TITLE
Docx to PDF/A converter embedded BOLD font problem

### ISSUE THREAD

**Issue by peterpeterparker** [opensagres/xdocreport#228]
As discussed in issue https://github.com/opensagres/xdocreport/issues/129 I have trouble converting Docx to PDF/A  if the source file contains BOLD font.

As simple example, I just created a Docs data containting the text **Test** (Calibri and Bold selected, [test.docx](https://github.com/opensagres/xdocreport/files/1174104/test.docx))

To be honest I really think there's no issue and the reason behind the problem is that I'm the problem aka that I'm missing something, but any help would be much appreciated :)

My mvn dependency:

    <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.xdocreport.core</artifactId>
            <version>1.0.5</version>
        </dependency>

My code:

    private byte[] generatePDFDocument(byte[] generateFrom) throws IOException, DocumentException {
		PdfOptions subOptions = PdfOptions.create();
		subOptions.setConfiguration( new IPdfWriterConfiguration()
		{

			public void configure( PdfWriter writer )
			{
				writer.setPdfVersion(PdfWriter.PDF_VERSION_1_4);

				writer.setTagged();

				PDFFontUtil.embedStandardFonts();

				writer.setPDFXConformance( PdfWriter.PDFA1A );
				writer.createXmpMetadata();
			}
		});

		subOptions.fontProvider(new IFontProvider() {

			@Override
			public Font getFont(String familyName, String encoding, float size, int style, Color color) {
				try {

					if (familyName.equalsIgnoreCase("CALIBRI")) {
						BaseFont baseFont =
								BaseFont.createFont("C:\\Windows\\Fonts\\" + (style == Font.BOLD ? "calibrib.ttf" : "calibri.ttf"), encoding, BaseFont.EMBEDDED);
						return new Font(baseFont, size, style, color);

					} 
				} catch (Exception e) {
					throw new RuntimeException(e);
				}

				return FontFactory.getFont(familyName, encoding, size, style, color);
			}
		});

		Options options = Options.getFrom(fr.opensagres.xdocreport.core.document.DocumentKind.DOCX).to(ConverterTypeTo.PDF).subOptions(subOptions);

		IConverter converter = ConverterRegistry.getRegistry().getConverter(options);

		ByteArrayOutputStream out = new ByteArrayOutputStream();

		try {
			converter.convert(new ByteArrayInputStream(generateFrom), out, options);
			return out.toByteArray();
		} catch (XDocConverterException e) {
			e.printStackTrace();
			return null;
		}
	}

Stacktrace:

Caused by: org.apache.poi.xwpf.converter.core.XWPFConverterException: org.apache.poi.xwpf.converter.core.XWPFConverterException: com.lowagie.text.DocumentException: com.lowagie.text.pdf.PdfXConformanceException: All the fonts must be embedded. This one isn't: Helvetica
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:70)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:38)
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45)
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67)
	... 192 more
Caused by: org.apache.poi.xwpf.converter.core.XWPFConverterException: com.lowagie.text.DocumentException: com.lowagie.text.pdf.PdfXConformanceException: All the fonts must be embedded. This one isn't: Helvetica
	at org.apache.poi.xwpf.converter.pdf.internal.elements.StylableDocument.flushTable(StylableDocument.java:349)
	at org.apache.poi.xwpf.converter.pdf.internal.elements.StylableDocument.close(StylableDocument.java:160)
	at org.apache.poi.xwpf.converter.pdf.internal.PdfMapper.endVisitDocument(PdfMapper.java:167)
	at org.apache.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:201)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:56)
	... 195 more
Caused by: com.lowagie.text.DocumentException: com.lowagie.text.pdf.PdfXConformanceException: All the fonts must be embedded. This one isn't: Helvetica
	at com.lowagie.text.pdf.PdfDocument.add(Unknown Source)
	at com.lowagie.text.Document.add(Unknown Source)
	at fr.opensagres.xdocreport.itext.extension.ExtendedDocument.add(ExtendedDocument.java:114)
	at org.apache.poi.xwpf.converter.pdf.internal.elements.StylableDocument.flushTable(StylableDocument.java:345)
	... 199 more
Caused by: com.lowagie.text.pdf.PdfXConformanceException: All the fonts must be embedded. This one isn't: Helvetica
	at com.lowagie.text.pdf.internal.PdfXConformanceImp.checkPDFXConformance(Unknown Source)
	at com.lowagie.text.pdf.PdfWriter.addSimple(Unknown Source)
	at com.lowagie.text.pdf.PdfContentByte.setFontAndSize(Unknown Source)
	at com.lowagie.text.pdf.PdfDocument.writeLineToContent(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.go(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.goComposite(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.go(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.go(Unknown Source)
	at com.lowagie.text.pdf.PdfPRow.writeCells(Unknown Source)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.goComposite(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.go(Unknown Source)
	at com.lowagie.text.pdf.ColumnText.go(Unknown Source)
	at com.lowagie.text.pdf.PdfDocument.addPTable(Unknown Source)
	... 203 more

**Comment by pensionarchitects-ben** [comment]
The stacktrace says you are missing Helvetica, try to add that one too. And see if the problem persist.

**Comment by peterpeterparker** [comment]
@pensionarchitects-ben is it? I thought Helvetica should not be embedded in a PDF/A since it's part of the default 14 fonts of iText

> There are 14 special fonts in PDF. We refer to them as the Standard Type 1 fonts. Every PDF viewer should be able to render text that uses those fonts, hence these fonts don't need to be embedded: 4 Helvetica fonts (regular, bold, italic, bold-italic), 4 Times Roman fonts (regular, bold, italic, bold-italic), 4 Courier fonts (regular, bold, italic, bold-italic), Symbol and Zapfdingbats.

http://developers.itextpdf.com/question/why-do-i-get-font-embedding-error-when-creating-pdfa1a

**Comment by pensionarchitects-ben** [comment]
Just try it, you are using a very old version of IText I don't know if they ignored it there to (It can be just be a faulty check in IText)

**Comment by peterpeterparker** [comment]
I'll try it (begin of next week) and will document the result. Thx for feedback

**Comment by peterpeterparker** [comment]
@pensionarchitects-ben Actually trying to set helvetica didn't solve my issue because only calibri, in my example, seems to be recognized

               @Override
		public Font getFont(String familyName, String encoding, float size, int style, Color color) {
			try {

				if (familyName.equalsIgnoreCase("CALIBRI")) {
					// <----- If I set a breakpoint, I always land here
				} 
			} catch (Exception e) {
				throw new RuntimeException(e);
			}

                        // If I set a breakpoint here, I never land in that place therefore
                        // can't embedd another font
			return FontFactory.getFont(familyName, encoding, size, style, color);
		} 

or did I misunderstood your idea?

about iText version, I use `2.1.7`

**Comment by pensionarchitects-ben** [comment]
I've searched a bit around and the only thing I can think of at the moment is that IText can't find your calibri font and just changes it to helvitica, make sure the path to the fonts are correct. If that doesn't change a thing try this 
```
FontFactory.Register("C:\\Windows\\Fonts\\georgia.ttf", "Georgia");
var georgia = FontFactory.GetFont("Georgia", 20f);
```

**Comment by peterpeterparker** [comment]
Thx for the idea, unfortunately it didn't solved my isse, same result :(

I then tried to generate the PDF without setting it as PDF/A to bypass the compleance. When I open the resulting PDF, I noticed that maybe the problem isn't `Calibri` but `ArialMT` (?) which seems to be interpreted as `Helvetica` (see screenshot)

But what I don't understand is, where does that comes from? `ArialMT` isn't use in the all document and even when I set a breakpoint in the overriden `getFont` method, another family than `Calibri` is never called...so weird

![2017-08-01 12_40_13](https://user-images.githubusercontent.com/16886711/28821752-00f9c22c-76b7-11e7-9744-6eee75e91449.png)

**Comment by peterpeterparker** [comment]
I just created a brand new document and a brand new simple project where I just use the same code as I presented above and I was able to produce a valid PDF/A with both bold and normal `Calibri` font.

No clue no idea why it didn't work and why not it does, but I least I have a valid minimal code to achieve my goal.

Thx a lot for your help and time @pensionarchitects-ben

For the record, here the dependencies I used:

    <dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.core</artifactId>
			<version>1.0.5</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter</artifactId>
			<version>1.0.5</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>org.apache.poi.xwpf.converter.pdf</artifactId>
			<version>1.0.5</version>
		</dependency>

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.xwpf</artifactId>
			<version>1.0.5</version>
		</dependency>

		<dependency>
			<groupId>com.lowagie</groupId>
			<artifactId>itext</artifactId>
			<version>2.1.7</version>
		</dependency>

**Comment by Droow** [comment]
Hi Peter, can you please put your minimal code somewhere? I just ran into exactly the same issue as you. Helvetica font is never used in the document, I'm even providing the missing Helvetica.ttf but as you said above, it never reaches the breakpoint - it only searches for Arial and Calibri. I'm using the same dependencies with same versions as you are and I can't get it to work.

**Comment by peterpeterparker** [comment]
@Droow sorry for my late answer, unfortunately can't really help, long time ago and I don't even work on that project/with that technology anymore, I hope you found a way

**Comment by why-qw1ko** [comment]
自定义字体即可解决

public class TurkishFontProvider extends AbstractFontRegistry {

    @Override
    protected String resolveFamilyName(String familyName, int style) {
        return familyName; // 直接透传，不做转换
    }
    @Override
    public Font getFont(String familyName, String encoding, float size, int style, Color color) {
        // 定义哪些字体名称应被替换为 NotoSansSC
        Set<String> westernFonts = new HashSet<>(Arrays.asList(
                "timesnewroman", "helvetica", "calibri",
                "sansserif", "serif", "", "dialog", "monospaced"
        ));

        String normalized = (familyName != null)
                ? familyName.replaceAll("\\s+", "").toLowerCase()
                : "";

        if (westernFonts.contains(normalized)) {
            try (InputStream is = getClass().getResourceAsStream("/fonts/你的字体.ttf")) {
                if (is == null) {
                    log.warn("NotoSansSC 字体未找到，fallback 到默认");
                    return super.getFont(familyName, encoding, size, style, color);
                }
                byte[] fontBytes;
                try (ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
                    int nRead;
                    byte[] data = new byte[1024];
                    while ((nRead = is.read(data, 0, data.length)) != -1) {
                        buffer.write(data, 0, nRead);
                    }
                    fontBytes = buffer.toByteArray();
                }
                BaseFont bf = BaseFont.createFont(
                        "/fonts/你的字体.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED,
                        true, fontBytes, null
                );
                return new Font(bf, size, style, color);
            } catch (Exception e) {
                log.error("加载 NotoSansSC 失败", e);
                return super.getFont(familyName, encoding, size, style, color);
            }
        }

        // 其他字体（如 SimSun）走默认逻辑
        return super.getFont(familyName, encoding, size, style, color);
    }
}


在调用处
pdfOptions.fontProvider(new TurkishFontProvider());

低版本的itext(2.1.7)
