### ISSUE TITLE
XDocReport and XML

### ISSUE THREAD

**Issue by lashower** [opensagres/xdocreport#23]
I'm trying to figure out how to port your DocxXMLProjectWithFreemarkerList.java over to a Velocity based implementation, but I'm a little lost on implementation.

When I went to https://code.google.com/p/xdocreport/wiki/VelocityTemplateContextXML, it said to "Use Velocity Anakia by registering a JDOM Document in the Java context." Does that mean I need to use Anakia to convert my xml to match your app's style? I naively thought I could just copy the code in step 1 and 2, modify it to match my variables and then it would work, but it looks like it will be more complicated than that. FYI, my end goal is to make a service where I just input the JDOM Element and merge the document with that.

Any help you could give me would be greatly appreciated.

**Comment by angelozerr** [comment]
@lashower your issues is about Velocity & XML (it's not really an issue for XDOcReport).

To be honnest with you, I have never played with XML & Velocity. It seems that Velocity & XML is supported by Anakia. So I suggest you to post your question on Velocity forum (use Velocity with XML)

**Comment by angelozerr** [comment]
None answer. I close this issue.
