### ISSUE TITLE
XDocReport Tools doesn't works with word 2013 on Windows 7 64bits

### ISSUE THREAD

**Issue by agonist** [opensagres/xdocreport#25]
Hi, I have an issue with the XDocReport Tools. After downloaded versions 1.0.4 and add it to my STARTUP word directory, It appear correctly in my word, but I can't use it cause of an error who tell me that the object is not available on this machine.

Also when I ctrl + F11 to open vba editor and try to open XDocReport I get "the project can't be displayed"

I use word 2013 + windows 7 64bits

anyone have fix this ?

**Comment by angelozerr** [comment]
Do you use https://github.com/opensagres/xdocreport/blob/master/document/fr.opensagres.xdocreport.document.tools/src/main/resources/macro/XDocReport_32bit_64bit.dotm ?

**Comment by agonist** [comment]
oh ! I didn't seen this one, I just replace it, and it's better now. I can now open the settings windows but when I click on "browse" to choose XML file, I get a compilation error.

**Comment by angelozerr** [comment]
@agonist we have no time to support this macro. Sorry.

Any contribution are welcome!
