### ISSUE TITLE
Incorrect logging in AbstractXDocReport

### ISSUE THREAD

**Issue by goekay** [opensagres/xdocreport#256]
The code in https://github.com/opensagres/xdocreport/blob/f6fbbe220fe9890e1737d478274ae789b273b5b3/document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/AbstractXDocReport.java#L719
logs "End convert report with error done with...." even though there are no errors. 
The same line can be seen in the exception catch block:
https://github.com/opensagres/xdocreport/blob/f6fbbe220fe9890e1737d478274ae789b273b5b3/document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/AbstractXDocReport.java#L728

Is this a copy/paste mistake?

**Comment by angelozerr** [comment]
Yes it's an error, please fix it with a PR. Thanks!
