### ISSUE TITLE
Problem with nested collection

### ISSUE THREAD

**Issue by Halcens** [opensagres/xdocreport#265]
Firstly, thanx for this project, it's great! 

Now I have a little problem, I have an object with nested collection (ufPackageList)

`public class MFPackage {

    private IImageProvider imageMFPackage;
    private String name;
    private String description;
    private List<UFPackage> ufPackageList = new ArrayList<UFPackage>();`

The MFPackage is also a nested collection in the parent object (RequirementDiagram) below the code : 

`public class RequirementDiagram {

    private Iterator requirementElements;
    private List mfPackage = new ArrayList();
    private List ufPackage = new ArrayList();
    private Iterator requirementObjects;
    private List<MFPackage> mfPackageObjectList = new ArrayList<MFPackage>();`

In my velocity template (docx) i did this : 

 `«#foreach($mfPackage in $mfPackages)» 
«$mfPackage.Name»
#foreach($ufPackage in $mfPackage["UfPackageList"])
1.12.3	«$ufPackage.Name»
«#end»
«#end»
`
The first loop mfPackage works but the nested collection ufPackageList doesn't work :(. 

I don't have error in my console, the doc is generated but the second loop is empty. 

Thanx you for you answer

**Comment by Halcens** [comment]
Hi, 

I found the solution, I did this syntax in my docx document 
`#foreach($mfPackage in $mfPackages)
«$mfPackage.Name»
 #foreach($ufPackage in $mfPackage.ufPackageList)`

I close the issue

**Comment by dgalicia9** [comment]
Sabes como se podría hacer en freemarker?
