### ISSUE TITLE
XDocConverterException thrown converting .odt to .pdf

### ISSUE THREAD

**Issue by PSFC** [opensagres/xdocreport#266]
Hello,

I'm trying to convert a document to .pdf using xdocreport v.2.0.1. If I use a .docx file and ConverterTypeVia.XWPF it works. If I use a .odt file and ConverterTypeVia.ODFDOM, I get an exception thrown:

fr.opensagres.xdocreport.converter.XDocConverterException: Cannot find converters from=ODT
	at fr.opensagres.xdocreport.converter.ConverterRegistry.internalFindConverter(ConverterRegistry.java:121)
	at fr.opensagres.xdocreport.converter.ConverterRegistry.findConverter(ConverterRegistry.java:74)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.getConverter(AbstractXDocReport.java:667)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:690)

I'm including all of the converters and document types in my pom file:

...
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.xwpf</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.ods</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.odt.odfdom</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.docx4j</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
...

Any help is highly appreciated.

**Comment by PSFC** [comment]
I was able to fix this by adding xerces to my .pom file:
...
<dependency>
	<groupId>xerces</groupId>
	<artifactId>xercesImpl</artifactId>
	<version>${xerces.version}</version>
</dependency>
...

**Comment by PSFC** [comment]
Reopened because this fix only works with xdocreport v2.0.0. When I went back to version 2.0.1 the problem returned.

**Comment by echiphn** [comment]
@PSFC could you please provide your odt file and block code to convert the file?

**Comment by semerkov** [comment]
Some dependencies which can help you:
                'fr.opensagres.xdocreport:fr.opensagres.xdocreport.core:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.document:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.template:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.template.freemarker:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.converter:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.converter.odt.odfdom:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.document.odt:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.odfdom.converter.core:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.odfdom.converter.xhtml:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.odfdom.converter.pdf:2.0.0',
		'fr.opensagres.xdocreport:fr.opensagres.xdocreport.itext.extension:2.0.0',
		'com.lowagie:itext:2.1.7',
		'org.odftoolkit:odfdom-java:0.8.7'

**Comment by PSFC** [comment]
Thanks, I'll try those and report back.
