### ISSUE TITLE
How to list template's fields before process the merge

### ISSUE THREAD

**Issue by Mimi6257** [opensagres/xdocreport#27]
Hi 

I'm using xDocReport 1.0.4 and I'm discovering it

I'm using 
fr\opensagres\xdocreport\samples\docxandfreemarker\DocxProjectWithFreemarkerAndImage.java  
for my test and I'm trying to list the freemarker of the template before any process.

I can list text freemarker with the method : 
------------------------------------------------------------------------------------

FieldsExtractor<FieldExtractor> extractor = new FieldsExtractor<FieldExtractor>();
report.extractFields(extractor);
List<FieldExtractor> fields = extractor.getFields();
for(FieldExtractor field : fields) System.out.println(field.getName());

-
Console : 
------------------------------------------------------------------------------------
project.name

-

I can see 'project.name' freemarker, but not all images (logo, originalSizeLogo, forcedSizeLogo, ... ) 

How can I list all variable of the template ?

My aim is to read a template, list all freemarkers, show them to the user, ask him to associate them to a text or an image , and them generate the result in docx, then in pdf.

Do you think it is possible with xDocReport ?

And if all of this is possible, can I read the size of the template's image in the aim to generate the new image with the same size ?

Thanks a lot for reading my issue

Regards

**Comment by angelozerr** [comment]
The extraction of simple field is managed with the template engien (Freemarker or Velocity). 

The extraction of field was just developped for our demo. But to be honnest with you, I think it's bad idea that fields comes from the docx/odt template.

For your need I suggest you that you study Freemarker template engine to know if it's possible to extract list, etc (I had searched but not found a solution, so any feedback are welcome!)

For the size of the template's image, please read https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainDynamicImage#Customize_size_of_image

**Comment by Mimi6257** [comment]
Hi

Thanks for your answer.

I have to read fields from template, because the template comes from the final user.

I simply use freemarker.template.Template to read the xml coming from the docx, and I'm looking for '${xxx}' syntaxe or bookmark in the word/document.xml
I can find the image size in the xml too, just have to convert them in pixel.
So after I made the field list, I put corresponding object into fr.opensagres.xdocreport.template.formatter.FieldsMetadata and 
fr.opensagres.xdocreport.template.IContext.
I'm sure that is not the best way, but at the time, it works.
If I find a better solution, I will share.

Thanks for your support and for the work you did with xDocReport :)
