### ISSUE TITLE
recover TextStyling for split instrText

### ISSUE THREAD

**Issue by muued** [opensagres/xdocreport#277]
In case instrText is split over multiple runs as considered by the code in [PBufferedRegion](https://github.com/opensagres/xdocreport/blob/002516484c2435ddd101657d24589817929c4472/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/PBufferedRegion.java#L146-L193), the text styling is lost, if the variable name is not part of the fist chunk ([since the first chunk is asked for its text styling](https://github.com/opensagres/xdocreport/blob/002516484c2435ddd101657d24589817929c4472/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/PBufferedRegion.java#L173-L174)).
Following the RBufferedRegion::setInstrText and MergefieldBufferedRegion::setInstrText calls we reach [MergefieldBufferedRegion::getFieldName](https://github.com/opensagres/xdocreport/blob/002516484c2435ddd101657d24589817929c4472/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/MergefieldBufferedRegion.java#L125), which [doesn't re-evaluate the text styling](https://github.com/opensagres/xdocreport/blob/002516484c2435ddd101657d24589817929c4472/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/MergefieldBufferedRegion.java#L184), but contains [all the magic needed to extract the variable name in the mergefield](https://github.com/opensagres/xdocreport/blob/002516484c2435ddd101657d24589817929c4472/document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/MergefieldBufferedRegion.java#L133-L182).

For me, two approaches to fix this suggest themselves:
1. ask the local TransformedBufferedDocumentContentHandler in the getFieldName call to re-evaluate the text styling in case there is none passed down the call hierarchy for the field in question
2. extract the magic to find the variable name in the instrtext mergefield string and re-use that code in the split-chunk code section in PBufferedRegion

**Comment by angelozerr** [comment]
Fix with https://github.com/opensagres/xdocreport/pull/278

Thanks @muued !
