### ISSUE TITLE
exclamation mark (Velocity special character) not supported in tables

### ISSUE THREAD

**Issue by clessiomendes** [opensagres/xdocreport#283]
In a nutshell, the [Quiet Reference Notation](http://velocity.apache.org/engine/devel/user-guide.html#quiet-reference-notation) exclamation mark "!" - interpreted by Velocity as a way to fill null values with blank - is not supported when [looping for fields in table row with FieldsMetadata](https://github.com/opensagres/xdocreport/wiki/DocxReportingJavaMainListFieldInTable).

If I create a table with a field name like $!developers.LastName, the engine can not match it when processing field substitutions and the result is a table rendered as empty. Removing the exclamation mark solves the problem, but raises other issues with null values.

Affected version: 1.0.4

[tableQuietIssue.docx](https://github.com/opensagres/xdocreport/files/1757092/tableQuietIssue.docx)

**Comment by gsancewicz** [comment]
I can try to solve this issue. It is related to #236.
