### ISSUE TITLE
Extra whitespaces during variable substitution

### ISSUE THREAD

**Issue by qdeme** [opensagres/xdocreport#295]
Hi,

We are using XDocReport to generate PDF documents for users using our online services.

But we are facing a blocking issue. We use $variables in the document, and each variable is replaced by the desired content, + an extra whitespace at the beginning of the text.

Example : "$identifiant" should be replaced by "STAGE-20180418-90IJ" but is actually replaced by " STAGE-20180418-90IJ".

And it is the case for every variable in the document. How can we avoid this behavior?

Please find attached our docx document and the generated PDF (we removed images and specific content purposely).

Thanks in advance for your help

[DemandeInfoCompl.docx](https://github.com/opensagres/xdocreport/files/1927140/DemandeInfoCompl.docx)
[courrierDEM_pk9_6477504130918884408.pdf](https://github.com/opensagres/xdocreport/files/1927141/courrierDEM_pk9_6477504130918884408.pdf)

**Comment by qdeme** [comment]
I'm sorry to comment again, but could anyone have a look about this problem?
If this problem is solved, this library would be used at a government level... otherwise we will find another way to generate our PDFs.
Best regards

**Comment by angelozerr** [comment]
Which version of XDocReport are you using? Have you the "extra space" problem if you generate docx instead of generating pdf?

**Comment by qdeme** [comment]
Thank you for your reply.
We are using version 2.0.1.
It seems that using the Ctrl+F9 and MergeField technique solves the problem... We were using the developer tab + tools ("form control") way.
Can you confirm this is the right thing to do?
Best regards

**Comment by angelozerr** [comment]
> It seems that using the Ctrl+F9 and MergeField technique solves the problem.

Indeed you must use mergefield. XDocReport provides too a macro to help to insert your field (not tested with last version of MS Word). I suggest you that you read https://github.com/opensagres/xdocreport/wiki/DocxReportingQuickStart

I close this issue, because the problem was that you didn't use mergefield.
