### ISSUE TITLE
«#if($entity.isShowMayAble)» is not working

### ISSUE THREAD

**Issue by Hongten** [opensagres/xdocreport#296]
Hi Team,

In my project, I encountered an issue which is «#if($entity.isShowMayAble)» is not working in the *.docx template. However, it works well if I use «#if($entity.ableToShowMay)».

The different is 
`private boolean isShowMayAble;`
`private boolean ableToShowMay;`

The reference Jar files:
![2018-04-25_123013](https://user-images.githubusercontent.com/3076703/39226358-8dc1e4ce-4884-11e8-818c-acfd255237ce.jpeg)

Test template: 
[DocxProjectWithVelocity_Hongten_Test.docx](https://github.com/opensagres/xdocreport/files/1945447/DocxProjectWithVelocity_Hongten_Test.docx)

Source code:
[src.zip](https://github.com/opensagres/xdocreport/files/1945460/src.zip)

Test result:
[DocxProjectWithVelocity_Hongten_Test_Output.docx](https://github.com/opensagres/xdocreport/files/1945449/DocxProjectWithVelocity_Hongten_Test_Output.docx)

Please advise.

Thanks.
Hongten

**Comment by angelozerr** [comment]
@Hongten it's a Velocity issue. I think you should write `$entity.showMayAble` and have a getter `boolean isShowMayAble()` in your bean. I think you can write too `$entity.isShowMayAble()`.

I close this issue since it's an issue of Velocity. If you have problem, please post your question on Velocity forum.

**Comment by Hongten** [comment]
@angelozerr Yes, you are correct. 

if I changed the getter method `isShowMayAble()` to `getIsShowMayAble()`, `$entity.isShowMayAble` is able to work.

```
public boolean isShowMayAble() {
    return isShowMayAble;
}
```
The method `isShowMayAble()` was generated by eclipse.

```
public boolean getIsShowMayAble() {
    return isShowMayAble;
}
```
The method `getIsShowMayAble()` was created by myself.

The test result as below:
![2018-04-25_143830](https://user-images.githubusercontent.com/3076703/39229716-64a618aa-4896-11e8-8359-118ba3cdeac2.jpeg)

Thanks @angelozerr again.

Hongten
