### ISSUE TITLE
Invalid version of freemarker jar in xdrtools.bat (for 1.0.4 release)

### ISSUE THREAD

**Issue by kaushalkumar** [opensagres/xdocreport#30]
What steps will reproduce the problem?
1. Preview throws an exception while using XDoc report macro
2. xdrtools.bat is referring to freemarker-2.3.18.jar, whereas freemarker-2.3.20.jar is packaged in lib folder

What is the expected output? What do you see instead?
Please change the version of freemarker jar in xdrtools.bat

What version of the product are you using? On what operating system?
1.0.4, Windows

**Comment by angelozerr** [comment]
Do you think it's possible to create a PR for that? Thanks

**Comment by kaushalkumar** [comment]
Done....can you please check https://github.com/opensagres/xdocreport/pull/32
