### ISSUE TITLE
Can you submit a new version to mvnrepository

### ISSUE THREAD

**Issue by lienjun** [opensagres/xdocreport#304]
In version 2.0.1,  the ColorHelper does not return the hexColor of the empty string directly, resulting in a subsequent NumberFormatException

**Comment by angelozerr** [comment]
@pascalleclercq have you time to do that?

**Comment by uded** [comment]
Would be nice to make a maintenance release. Also, maybe some clean up of dependencies and easier-to-understand guide on what to include when would be nice as well... but time-consuming.

**Comment by angelozerr** [comment]
2.0.3 has been released. Thanks so much @pascalleclercq !
