### ISSUE TITLE
convert docx(table) to pdf, but I want Cross-page break

### ISSUE THREAD

**Issue by xi-mad** [opensagres/xdocreport#318]
**this is source docx**
![1](https://user-images.githubusercontent.com/26453680/43398094-a19503f4-9439-11e8-9c1a-98c7487f00ba.png)

**I get this**
![2](https://user-images.githubusercontent.com/26453680/43398096-a2446fc4-9439-11e8-91ba-f7be10267dc2.png)

**but I want this**
![3](https://user-images.githubusercontent.com/26453680/43398099-a29846f8-9439-11e8-95dc-05b60b7cd54f.png)

code here:
```
    private void word2PDF(XWPFDocument doc, OutputStream target) throws IOException {
        PdfOptions options = PdfOptions.create();
        PdfConverter.getInstance().convert(doc, target, options);
    }
```

does anyone know this?

**Comment by kan2008tnptc** [comment]
@xi-mad Hi,, have you figured out the issue? I am also facing the same issue.

**Comment by xi-mad** [comment]
@kan2008tnptc  I am so sorry, I have no idea about this.
