### ISSUE TITLE
Upgrade POI

### ISSUE THREAD

**Issue by nelsongraca** [opensagres/xdocreport#349]
I wonder if it is possible to upgrade POI to 4.x I am currently evaluating using this library to convert some DOCX to PDF in a project but we already depend on v4 so this causes a conflict.

**Comment by esuomi** [comment]
FWIW, POI 4.x is also needed for JDK11 compatibility.

**Comment by angelozerr** [comment]
Thanks @esuomi for this info. In this case , I would like to avoid doing that since XDocReport works with Java5.

**Comment by nelsongraca** [comment]
@angelozerr so you will keep it without upgrading?

**Comment by angelozerr** [comment]
Jdt 11 is too young and there are aa lot People Who uses java 5. I prefer waiting That there are à Lot of People Who Use java 11 before switching to java 11. Please add +1or-1 to switch to java 11

**Comment by nelsongraca** [comment]
I'm using POI 4.x on JDK8 I dare to say that POI4.x adds support for JDK11, from what @esuomi said it does not imply that other versions support is dropped. As you might be aware except a very small set of things the JDK has been backwards compatible.

**Comment by nelsongraca** [comment]
I would also like to add that without the POI upgrade I will have to fork the project in order to be able to use it, and I would like to avoid that.

**Comment by esuomi** [comment]
@angelozerr  _Technically_ POI 4.x is needed when going beyond Java 8, I mentioned JDK11 just because that's the latest&greatest.

**Comment by angelozerr** [comment]
> it does not imply that other versions support is dropped

Sorry I have read too quickly. @nelsongraca please create a PR in order to I see which files are impacted (is java code package is impacted?)

**Comment by nelsongraca** [comment]
Java package impact should be zero. @angelozerr I will submit a PR in the next hours with the changed needed.

**Comment by nelsongraca** [comment]
@angelozerr created #352 tests are failing will check now, but this is the main impact.

**Comment by nelsongraca** [comment]
Tests are now passing.

**Comment by esuomi** [comment]
@nelsongraca Thank you for creating this patch already in advance :)
@angelozerr When would you estimate to have this merged and released? Considering its urgency for all Java 9+ users having a public snapshot/beta release as soon as possible would do just fine while you assess the wider impact, if any.

**Comment by nelsongraca** [comment]
Like @esuomi I would like to have this available ASAP since I'm depending on it to integrate with some projects.

**Comment by nelsongraca** [comment]
#352 Merged, closing issue, waiting on next release. Thank you.

**Comment by esuomi** [comment]
Echoing what @nelsongraca said, especially the thanks part! :)

**Comment by bvsvas** [comment]
@nelsongraca You upgrade POI to 4.0.1. We are still using POI 3.17. Could you please let us know what are the extra commons dependencies required to use POI 4.0.1 as you are already using it. I knew it requires commons-compress and anything else?
