### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by dseiler** [opensagres/xdocreport#35]
Hi, does xdocreport support formatting of dates in merge fields?
E.g. 

{
MERGEFIELD $myDate @date('dd.MM.yyy') \* MERGEFORMAT
}

@pascalleclercq @tiry @alediator @julien-sobczak @angelozerr 
Would be a great feature!

Thanks a lot

Daniel

**Comment by angelozerr** [comment]
No it doesn't support. You must use Velocity/Freemarker syntax if you wish to format field.

**Comment by dseiler** [comment]
Thanks. That was what I initially tried. I create a merge field which looked something like this in word:
MERGEFIELD $date.format('medium', $myDate)
Unfortunately without success.
Could you please give me an example how to us velocity syntax in a MS Word template which works with  xdocreport.

Thanks a lot!

Daniel

**Comment by angelozerr** [comment]
> Unfortunately without success.

What do you mean? Stacktrace?

**Comment by dseiler** [comment]
Hi, I created my own Java class to do the formatting, and added this class to the xdoc report context. Now I am able to format date and numbers as I like! Great!

Another question (please let me know if there is a better place to post questions like this): Is there a way to create Docx templates with a table which has alternating row colours? I have my merge data with and index variable on each record and tried it with at before-row and if statements, but without success.

**Comment by angelozerr** [comment]
> Now I am able to format date and numbers as I like! Great!

That's cool.

> Is there a way to create Docx templates with a table which has alternating row colours? 

Please read https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainListFieldAdvancedTable

I close this issue.
