### ISSUE TITLE
Release 2.0.2 is not on maven central

### ISSUE THREAD

**Issue by eijckron** [opensagres/xdocreport#353]
Although version 2.0.2 has been tagged and is downloadable it is not available on maven central which makes it harder to use it from projects.

**Comment by angelozerr** [comment]
@pascalleclercq could you help us with this problem please. Thanks!

**Comment by nelsongraca** [comment]
From what I see it is now, this should be closed.

**Comment by angelozerr** [comment]
2.0.3 has been released. Thanks so much @pascalleclercq !
