### ISSUE TITLE
Xdocreport markdown/HTml Style is not working for List type objects

### ISSUE THREAD

**Issue by vdumpala** [opensagres/xdocreport#386]
i am working on Rich text content which is markdown to display in DOCX. 
it is working if i give single one text "contentdescription" attribute .but it is not working if i have attrbute in the list like  "attachment.contentdescription" . 
is it not yet in implemented part of the current release ?  
I have other types for List with images are working fine..  only see issue with styling for list.
let me know if there is any alternative.
                fieldsMetadata.addFieldAsList("attachment.contentDescription");
                fieldsMetadata.addFieldAsTextStyling("attachment.contentDescription",
                        SyntaxKind.MarkDown );

**Comment by angelozerr** [comment]
No time to work on XDocReport today. If you need this feature please create a PR

**Comment by angelozerr** [comment]
> as i created this 3 days ago. did you get a chance to work on it ?

No,as I explained you, I have no time to work on XDocReport today. This project continues to improve it with several contributions that we have the luck to have, but me I have no time to work on it. Any contribution are welcome!

**Comment by vdumpala** [comment]
ohh ok thanks sure I will try that when I get a chance. as it is urgent i requested this.

**Comment by vdumpala** [comment]
Hi angelozerr ,  i tried to fix the problem. i couldnt able to figure out the problem. could you help on this as i have one day to fix this issue. is there any alternative to fix this issue with out changing the code ?

**Comment by vdumpala** [comment]
hi angelozerr. this is working fine. as i see this issue happening when you have two bookmark images. i made it as one bookmark image.  When you responded me to fix the code i thought your api is not working. that made to wait. but you can close this issue now . thanks

**Comment by angelozerr** [comment]
Glad you fixed your problem.
