### ISSUE TITLE
Support for OpenPDF

### ISSUE THREAD

**Issue by yogeshrao** [opensagres/xdocreport#387]
Hi,

I noticed xdocreport works with iText (v2.1.7 - LGPL) which was released in Jul 2009. The project has been forked as OpenPDF and few fixes are available in the forked branch.

I was wondering if OpenPDF support can be introduced as a new extension to xdocreport, which eventually can be used to phase out the ageing iText extension.

Happy to contribute...

Please let me know.

Regards,
-Yogesh

**Comment by goekay** [comment]
this is technically possible. but as pointed out [by the developer of itext](https://github.com/opensagres/xdocreport/issues/258#issuecomment-355252927), there seem to be a license and copyright problem.

**Comment by yogeshrao** [comment]
I have opened a Pull Request for adding support for OpenPDF.

**Comment by angelozerr** [comment]
Thank a lot @yogeshrao ! @Dimitriio could you review it please?

@goekay do you think we could merge the work on @yogeshrao?

**Comment by goekay** [comment]
@angelozerr i am just an outsider and not a core dev of xdocreport, so you are free to ignore me but imho, these are _a lot_ of changes in one commit. it's hard to review what's going on without the work being split in multiple, semantically grouped commits. furthermore, my latest state of knowledge was that openpdf was compatible with itext w.r.t. api and namespaces. therefore i ask myself why so many changes are necessary. one possible answer is that the classes were just copied and pasted with only minimal changes applied. this would be a maintenance nightmare. @yogeshrao can you please elaborate on your thinking process? as i said, i am not a regular contributor/dev, feel free to ignore me.

**Comment by angelozerr** [comment]
> feel free to ignore me.

No way! To be honnest with you, I have no time to contribute to XDcoReport so the project lives with the contribution and any comments from any people are important. I will not have time to review the code and I trust the community to provide this OpenPDF support.

**Comment by Dimitriio** [comment]
Yeah I posted a pull request for the update (can see it above, #401 ) where I updated from itext to openpdf.
I think the approach of @yogeshrao is more a new extension with openpdf, with I guess copy/paste, than an update.

**Comment by yogeshrao** [comment]
@goekay 

Following was the thought process behind this commit - 

1. xdocreport already has support for iText and iText 5, I am sure users using itext would continue to see it supported going forward any disruption around this might not be good for the users.
2. OpenPDF is a fork and has few changes w.r.t to APIs over iText and i am sure this would evolve going forward and perhaps someday might even bring in a change with respect to namespaces. ( I will be posting on the group to figure out if they have plans for the same and perhaps contribute there as well).
3. While I certainly feel  current project layout / structure can be improved (a separate issue might comeup on this soon) cloning iText extension and making necessary changes was the only way forward. 
4. This commit introduces OpenPDF support into xdocreport and is not replacing iText support, If we want xdocreport users to move on to OpenPDF then iText extension has to be marked deprecated which gives users necessary time to decide and move to OpenPDF.

@Dimitriio Yes its a clone and not a replacement to iText for above reasons.

**Comment by goekay** [comment]
@yogeshrao thanks for the detailed explanation. i appreciate it. your reasoning aligns with my assumption and i can understand it. however, i still think, this way of a feature introduction makes it hard to maintain the codebase. as an example [this method](https://github.com/opensagres/xdocreport/blob/master/thirdparties-extension/fr.opensagres.xdocreport.itext.extension/src/main/java/fr/opensagres/xdocreport/itext/extension/ExtendedPdfPTable.java#L87-L133) is exactly the same in all three extensions itext, itext5 and now openpdf. all i am saying is, that i as a developer would have an uneasy feeling about this much duplicate code. i think i don't need to go on about the benefits of DRY.

wouldn't it be better to rethink and rearchitect this part of the code?

one possible solution that easily comes to mind is having one pdf extension as the primary source of the business logic and making others just wrappers around this primary one. therefore, other pdf extensions internally use, depend on and wrap this primary extension. this way, users of the (old) itext can continue using it.

**Comment by Dimitriio** [comment]
I was thinking same at first, like duplicating but I know that usually it's not the best approach to copy/paste code for future maintenance and as the itext extension was based on itext 2.1.7 which was published in 2009 (if I remember correctly).
I thought that it wont be a miss to change it into the opensource fork (as its the same licence).
But its true that if some part of itext is exposed to users, it can be a better approach to make it deprecated and continue on a new extension.

**Comment by yogeshrao** [comment]
@goekay 

I understand the repeatable code across similar modules is a problem, unfortunately that is how present code base is with iText and iText5.

IMO I wouldn't bring in refactoring of code with introduction of new support as part of 1 commit as it makes it too complex to track.

At this point i can suggest following approaches -

Approach 1
1. Release the current code base with recent fixes
2. Work on 2.0 release which is a refactored version of the entire code base / project structure and not just extensions. (One big project getting released always is not really the ideal one w.r.t deployment and maintenance)
3. And then introduce OpenPDF support

Approach 2
1. Accept the OpenPDF commit as its introducing new Support
2. Work on 2.0 release which might break backward compatibility w.r.t to users or iText, iText5 and OpenPDF

Approach 1 would take longer time compared to Approach 2. Approach 2 will have some discomfort for a short while.

Which one would the group like to choose ?

@Dimitriio Thank you..

**Comment by goekay** [comment]
regarding approach 1: it's a _huge_ undertaking to refactor the entire code base and structure, which can be very error prone. i would shy away from it.

what about a 3rd approach i illustrated above? we can look at the pdf extension impls (itext/itext5/openpdf) to understand which impl is the most feature rich. then, we can use it as the primary source for business logic. since other pdf extensions are subsets (feature wise) they can wrap the most feature-rich one and use parts of it employing the delegation pattern and/or mappers for data types (if necessary). 

i used this approach in a project with success to support multiple versions of a communication protocol. as a result, there is no duplicate code. if i detect and fix a bug in my business logic or need to change a behaviour, i only need to touch one place and all versions are fixed.

**Comment by yogeshrao** [comment]
@goekay 

I do not think you can derive commonalities of all the three PDF implementations. 

A quick search to understand the difference between iText vs iText 5 can be found [here](https://itextpdf.com/en/resources/faq/legal/itext-5-legacy/what-difference-between-lowagie-and-itext). Based on the link the package names have changed and new standards around PDF have supported.

On iText vs OpenPDF, it makes me believe few fixes of iText 5 have made its way into OpenPDF along with its own. 

All in all my understanding is none of the library can be a drop in replacement for the other(subset) which would make delegation pattern possible for you.

Let me know if you think otherwise.

Disclaimer: My knowledge is very limited when it comes across these different versions of PDF library

Regards,
-Yogesh

**Comment by goekay** [comment]
@yogeshrao i did not mean the pdf libraries (itext/itext5/openpdf) themselves, which xdocreport uses just as a library. they are the backends of pdf extensions in xdocreport. the pdf extensions are the frontends, if you will. i meant to restructure these extension implementations, the frontends, since the source code for these are the same (for the most part).

i sure can derive commonalities in these extensions. i gave the method example above. here is `ExtendedPdfPTable` class as an enhanced example:
- [in itext](https://github.com/opensagres/xdocreport/blob/master/thirdparties-extension/fr.opensagres.xdocreport.itext.extension/src/main/java/fr/opensagres/xdocreport/itext/extension/ExtendedPdfPTable.java)
- [in itext5](https://github.com/opensagres/xdocreport/blob/master/thirdparties-extension/fr.opensagres.xdocreport.itext5.extension/src/main/java/fr/opensagres/xdocreport/itext/extension/ExtendedPdfPTable.java)
- [in openpdf](https://github.com/yogeshrao/xdocreport/blob/master/thirdparties-extension/fr.opensagres.xdocreport.openpdf.extension/src/main/java/fr/opensagres/xdocreport/openpdf/extension/ExtendedPdfPTable.java)

they are practically the same class (and contain the same logic, which has to be maintained, which is our discussion topic) with the following exception: the call `cell.setBorder( Table.NO_BORDER );` becomes `cell.setBorder( Rectangle.NO_BORDER );` in itext5 extension. `NO_BORDER` is just a final field that points to the magic number 0 and now resides in a different class.

**Comment by yogeshrao** [comment]
@goekay 

Apologies for the delayed response.

How do you plan to tackle `public class ExtendedPdfPTable extends PdfPTable` where `PdfPTable` can come in from `com.lowagie.text.pdf.PdfPTable` for Itext and OpenPDF and `com.itextpdf.text.pdf.PdfPTable` ?

From what i understood you would prefer to code `cell.setBorder( 0 );` instead of `cell.setBorder( XXXX.NO_BORDER );`. I would avoid setting the value directly to 0 as no one would understand the option getting set here and will have to refer to documentation around code or else to understand the values being set.

Having said this I do not want to hold you back from making the changes, However my take is we perhaps are over complicating the task as Xdocreport will have to at some point deprecate iText (v2.1.7) and iText (v5) support in near future.

Regards,
-Yogesh

**Comment by andreasrosdal** [comment]
Thanks for the interest in using OpenPDF! Please let me know if you want some changes made to OpenPDF, or if you want to contribute to the project, in order for you to make better use of the library. I'm one on the maintainers of OpenPDF. We just had a new release of OpenPDF, which you might find useful. 

OpenPDF is an open source project where we welcome contributions from the community. It has a dual LGPL/MPL license, and is used in accordance with this license in the original source code published by iText on Sourceforge. We have done a code license review and it is clear that OpenPDF uses the source code in accordance with the LGPL/MPL license.

**Comment by yogeshrao** [comment]
@angelozerr , @goekay , @Dimitriio 

How do we proceed ahead on this? I see our product moving to OpenPDF very soon and hence was keen to know if XDocReport would support.

Regards,
-Yogesh

**Comment by codecracker2014** [comment]
@angelozerr changes done in #401 seems to be fine, can this be merged. How about using OpenPDF in further releases instead of itext?

**Comment by codecracker2014** [comment]
@angelozerr when you are planning to merge #401.

**Comment by andreasrosdal** [comment]
This looks great, and can be merged.

**Comment by yogeshrao** [comment]
@andreasrosdal 

Thank you for the update...

I think now its up to @angelozerr , @goekay , @Dimitriio to decide if they want to merge.

Regards,
-Yogesh

**Comment by angelozerr** [comment]
If @goekay , @Dimitriio  are OK, I will merge the PR.

**Comment by andreasrosdal** [comment]
I recommend updating to OpenPDF version 1.3.18, which is the latest version now

**Comment by yogeshrao** [comment]
@andreasrosdal 

That can go as part of new issue if thats okay.

**Comment by andreasrosdal** [comment]
yes

**Comment by angelozerr** [comment]
2.0.3 has been released and it provides openpdf support. Many thanks fir all people who contributed to openpdf support!
