### ISSUE TITLE
List and images

### ISSUE THREAD

**Issue by juggy** [opensagres/xdocreport#40]
More a question than an issue. 

Within list fields https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainListFieldAnywhere, can you add images? If so how?

**Comment by angelozerr** [comment]
Imagine that Developer class returns an image (inputStream or IImageProvider )

Create a template image in your docx (see https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainDynamicImage) and add loop start/end : 

```
#foreach($developer in $developers)
  $developer.Image
#end
```

And after mark the developer image field as image.

```java
metadata.addFieldAsImage("developer.Image");
```

or you can use @FieldMetadata annotation https://code.google.com/p/xdocreport/wiki/FieldsMetadataTemplate. If I remember you have an @ImageMetadata

**Comment by angelozerr** [comment]
None answer, I close this issue.

**Comment by yuchen99** [comment]
···
#foreach($developer in $developers)
  $developer.Image
#end
···
just out put fr.opensagres.xdocreport.document.images.FileImageProvider@457e2f02

**Comment by goraxan** [comment]
Not working, it outputs fr.opensagres.xdocreport.document.images.FileImageProvider@... as @yuchen99 said

**Comment by fahadmaq007** [comment]
I had a tough time trying to figure out what's going on. Had similar issues as @yuchen99 and @goraxan. Happy to share that I finally managed to got it working. Initially I was trying to load the image from Map<String, Object>, when changed it to normal POJO (like DeveloperWithImage.java), it started working. `metadata.load( "photos", Photo.class, true );`

**Comment by gladshop** [comment]
> ···
> #foreach($developer in $developers)
> $developer.Image
> #end
> ···
> just out put fr.opensagres.xdocreport.document.images.FileImageProvider@457e2f02

I have same problem, does you have any way to fix this problem?
