### ISSUE TITLE
Requesting Release of xdocreport version 2.0.3

### ISSUE THREAD

**Issue by sammad** [opensagres/xdocreport#406]
Hello,

Just wanted to know the date of release of xdocreport new version i.e. 2.0.3 Our product needs one of the fixes done in this scope.

**Comment by sammad** [comment]
Can anyone point me to Release process of xdocreport,. In case no one has  bandwidth to release the library, I am willing to do so.

**Comment by angelozerr** [comment]
Before releasing we need to fix completion problem (with java 11).  I think it's just add some depenedency POM because javax.activation doesn't exists. See travis https://travis-ci.org/opensagres/xdocreport/jobs/630869775#L1741

@pascalleclercq could you help us with this process please. thanks!

**Comment by sdahlberg** [comment]
Any chance of seeing a release soon?

**Comment by codecracker2014** [comment]
@angelozerr when release is planned? are we waiting for any fix?

**Comment by angelozerr** [comment]
I would like to really delegate this task to a new active contributor, because me and @pascalleclercq have no time to work on XDocReport.

**Comment by codecracker2014** [comment]
@angelozerr let me know how i can help here.

**Comment by angelozerr** [comment]
2.0.3 has been released. Thanks so much @pascalleclercq !
