### ISSUE TITLE
docx to pdf using itext underline is thick

### ISSUE THREAD

**Issue by codecracker2014** [opensagres/xdocreport#408]
Underline in output PDF is thick, which is very thin in docx. Below are snapshots of the same:

Docx:
![image](https://user-images.githubusercontent.com/6597998/73904982-d1913b00-48c3-11ea-9faf-af39e18bc41d.png)

PDF
![image](https://user-images.githubusercontent.com/6597998/73904958-b45c6c80-48c3-11ea-8f7e-4ff64729dcdb.png)

This is due to below code in PDFMapper
textChunk.setUnderline( 1, -2 );
which should be 
textChunk.setUnderline( 0.1F, -2 );

**Comment by angelozerr** [comment]
Fixed with https://github.com/opensagres/xdocreport/pull/409
