### ISSUE TITLE
Saving *.docx generates ParseException: <w:fldSimple becomes <w:instrText

### ISSUE THREAD

**Issue by dnmd** [opensagres/xdocreport#42]
Also, let me start by giving a big shout out for this excellent library! Many thanks!

I'm running into an issue, which is somewhat mentioned in #3 and #38, but not very explicitly. When adding and removing just as little as a space in a *.docx file, the document.xml gets (sometimes) optimized. Changing a `<w:fldSimple` into `<w:instrText` and consequently breaking the generation process (see the XML code for a single mergefield). Is the anything I can do (on the backend or in MS Word itself)? Or does someone has a workaround?

Many thanks in advance and keep up the good work!

````xml
<w:fldSimple w:instr=" MERGEFIELD  ${name}  \* MERGEFORMAT ">
	<w:r w:rsidR="0092309C">
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:t>«${name}»</w:t>
	</w:r>
</w:fldSimple>
````
... becomes

````xml
<w:r>
	<w:fldChar w:fldCharType="begin"/>
</w:r>
<w:r>
	<w:instrText xml:space="preserve"> MERGEFIELD  ${name}  \* MERGEFORMAT </w:instrText>
</w:r>
<w:r>
	<w:fldChar w:fldCharType="separate"/>
</w:r>
<w:r w:rsidR="0092309C">
	<w:rPr>
		<w:noProof/>
	</w:rPr>
	<w:t>«${name}»</w:t>
</w:r>
<w:r>
	<w:rPr>
		<w:noProof/>
	</w:rPr>
	<w:fldChar w:fldCharType="end"/>
</w:r>
````

**Comment by angelozerr** [comment]
XDocReport supports the both syntax for mergefield. Please share your docx +Java context which causes problem.

**Comment by dnmd** [comment]
The repo can be found here: https://github.com/dnmd/xdocreport 
It boils down to the following: when opening the *.docx, adding and removing a space and save it;
- the *.docx gets optimized, changing the syntax to: [line 34](https://github.com/dnmd/xdocreport/blob/master/DocxProjectWithFreemarkerList.java#L34)
- **then it fails over [line 72](https://github.com/dnmd/xdocreport/blob/master/DocxProjectWithFreemarkerList.java#L72)**
- when you repeat the process (adding and removing a space), the syntax becomes "unoptimized" again:  [line 51](https://github.com/dnmd/xdocreport/blob/master/DocxProjectWithFreemarkerList.java#L51) and all works again.

**Comment by angelozerr** [comment]
@dnmd tahnks for your explanation.

Could you please share too your docx which causes problem (which contains w:instrText xml:space="preserve"> MERGEFIELD  ${acuOther.cond}  \* MER</w:instrText>)?

**Comment by dnmd** [comment]
It is in the repo, here's the direct link: https://github.com/dnmd/xdocreport/blob/master/DocxProjectWithFreemarkerList.docx?raw=true

**Comment by angelozerr** [comment]
That's strange, your word/document.xml doesn't contains contains 

```xml
<w:r>
					<w:instrText xml:space="preserve"> MERGEFIELD  ${acuOther.cond}  \* MER</w:instrText>
				</w:r>
				<w:r>
					<w:instrText xml:space="preserve">GEFORMAT </w:instrText>
				</w:r>
```

but it contains 

```xml
<w:fldSimple w:instr=" MERGEFIELD  ${acuOther.cond}  \* MERGEFORMAT ">
					<w:r w:rsidR="00D84AC9" w:rsidRPr="00021809">
						<w:rPr>
							<w:noProof/>
						</w:rPr>
						<w:t>«${acuOther.cond}»</w:t>
					</w:r>
				</w:fldSimple>
```

**Comment by dnmd** [comment]
Here's the directly failing word document https://github.com/dnmd/xdocreport/blob/master/DocxProjectWithFreemarkerList_fails.docx?raw=true

**Comment by angelozerr** [comment]
Thanks. It will help me a lot if you could create a JUnit like https://github.com/opensagres/xdocreport/blob/master/integrationtests/fr.opensagres.xdocreport.core.test/src/test/java/fr/opensagres/xdocreport/document/docx/preprocessor/Issue401.java

**Comment by dnmd** [comment]
I've created and pushed the JUnit to my repo. Here is the direct link: https://github.com/dnmd/xdocreport/blob/master/Issue42.java 

Hope that helps! 

Even though it is difficult for me to interpret the JUnit results and this is pure guessing, it might related to the a table style "Table Grid" (`<w:tblStyle w:val="TableGrid"/>`) that is applied to all tables. But I am no expert. 

Thanks anyway for this great project!

**Comment by angelozerr** [comment]
@dnmd I have fixed the problem, please tell me if it works for you.

**Comment by dnmd** [comment]
Amazing, many many thanks, the first tests look promising (no ParseExceptions so far). I used the build https://opensagres.ci.cloudbees.com/job/xdocreport/682/ build. 

I've read you are very busy with a lot of open source projects, and I hate to ask, but do you have plans on releasing any new versions of XDocReport in the near future? Merci beaucoup! :)

**Comment by angelozerr** [comment]
> new versions of XDocReport in the near future

Release is done by @pascalleclercq. I don't know when he will have time to do that and I think we should have a little more features before creating a release.

> Merci beaucoup! :)

:)
