### ISSUE TITLE
Support html text styling <sub> and <sup> for docx

### ISSUE THREAD

**Issue by angelozerr** [opensagres/xdocreport#43]
See https://code.google.com/p/xdocreport/issues/detail?id=484

**Comment by StalAlexandr** [comment]
Hi Angelo! 
Thank you again for your help!

There is small problem with tag closing.  
For example, my code is 

IContext context = report.createContext();
FieldsMetadata fmd = report.createFieldsMetadata();
fmd.addFieldAsTextStyling("title", SyntaxKind.Html);
String s = "Drink H<SUB>2</SUB>O  it is cool";
context.put("title", s);

I expect to get just char  '2' at subscript, but I got '2O it is cool' at subscript
![testsub](https://cloud.githubusercontent.com/assets/7043838/8278901/ef9ae1e4-18d7-11e5-8115-88eff352119b.png)
