### ISSUE TITLE
Unable to upgrade to POI 5.0.0 with fr.opensagres.poi.xwpf.converter.pdf (2.0.2)

### ISSUE THREAD

**Issue by pradeep-nagarajan** [opensagres/xdocreport#464]
Getting the below error,

Caused by: java.lang.NoSuchMethodError: org.openxmlformats.schemas.wordprocessingml.x2006.main.CTStyle.getDefault()Lorg/openxmlformats/schemas/wordprocessingml/x2006/main/STOnOff$Enum;
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.initialize(XWPFStylesDocument.java:273)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:226)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:196)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:190)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.createStylesDocument(XWPFDocumentVisitor.java:182)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.<init>(XWPFDocumentVisitor.java:175)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.<init>(PdfMapper.java:155)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:56)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)

**Comment by joaonatalio** [comment]
Similar issue observed in the `fr.opensagres.xdocreport.converter.docx.xwpf` artifact. Is there a plan to adapt to POI 5.0.0?

**Comment by alexsukhodolsky** [comment]
@joaonatalio any luck figuring this one out?

**Comment by rzo1** [comment]
This most certainly requires an upgrade and code adjustments in `fr.opensagres.poi.xwpf.converter.core` as the library uses `CT` classes directly. This is also stated in the POI 5.0.0 release notes:
```

 Upgrade to ECMA-376 5th edition (transitional) schemas - expect API breaks when using XmlBeans directly
  some smaller changes are necessary when code is using the low-level CT... classes 

```
https://downloads.apache.org/poi/release/RELEASE-NOTES.txt

**Comment by t-oster** [comment]
Any updates to this? Can someone please post the latest working combo for 

fr.opensagres.poi.xwpf.converter.pdf
and POI as pom.xml?

**Comment by kdebski85** [comment]
I can see that there is a commit which should fix it - https://github.com/opensagres/xdocreport/commit/628de077cc9446d2ee2ae967b40285c0769cecb9

When xdocreport with the fix will be released?

**Comment by angelozerr** [comment]
@pascalleclercq do you think you will have some time to create a release?

**Comment by pascalleclercq** [comment]
Unfortunatly I have several failure in the build on my laptop 
[INFO] XDocReport 2.0.3-SNAPSHOT .......................... SUCCESS [  0.534 s]
[INFO] XDocReport third parties extensions ................ SUCCESS [  0.031 s]
[INFO] fr.opensagres.poi.xwpf.converter.core .............. SUCCESS [  8.062 s]
[INFO] fr.opensagres.xdocreport.itext.extension ........... SUCCESS [  1.883 s]
[INFO] fr.opensagres.poi.xwpf.converter.pdf ............... SUCCESS [ 51.690 s]
[INFO] XDocReport Core Component .......................... SUCCESS [  0.047 s]
[INFO] fr.opensagres.xdocreport.core ...................... SUCCESS [  3.774 s]
[INFO] fr.opensagres.poi.xwpf.converter.xhtml ............. SUCCESS [ 30.872 s]
[INFO] fr.opensagres.odfdom.converter.core ................ SUCCESS [  0.723 s]
[INFO] fr.opensagres.odfdom.converter.pdf ................. SUCCESS [ 14.165 s]
[INFO] fr.opensagres.odfdom.converter.xhtml ............... SUCCESS [  4.303 s]
[INFO] XDocReport Template Component ...................... SUCCESS [  0.032 s]
[INFO] fr.opensagres.xdocreport.template .................. SUCCESS [  1.552 s]
[INFO] XDocReport Converter implementation ................ SUCCESS [  0.015 s]
[INFO] fr.opensagres.xdocreport.converter ................. SUCCESS [  1.098 s]
[INFO] XDocReport Document Component ...................... SUCCESS [  0.031 s]
[INFO] fr.opensagres.xdocreport.document .................. SUCCESS [  4.364 s]
[INFO] fr.opensagres.struts2.views.xdocreport ............. SUCCESS [  0.516 s]
[INFO] fr.opensagres.web.servlet.view.xdocreport .......... SUCCESS [  0.322 s]
[INFO] fr.opensagres.xdocreport.itext5.extension .......... SUCCESS [  2.480 s]
[INFO] fr.opensagres.poi.xwpf.converter.pdf.itext5 ........ SUCCESS [ 32.167 s]
[INFO] fr.opensagres.odfdom.converter.pdf.itext5 .......... SUCCESS [  9.542 s]
[INFO] fr.opensagres.xdocreport.openpdf.extension ......... SUCCESS [  2.059 s]
[INFO] fr.opensagres.poi.xwpf.converter.pdf.openpdf ....... SUCCESS [01:10 min]
[INFO] fr.opensagres.odfdom.converter.pdf.openpdf ......... SUCCESS [ 15.783 s]
[INFO] XDocReport Core Component .......................... SUCCESS [  0.016 s]
[INFO] fr.opensagres.xdocreport.remoting.api .............. SUCCESS [  0.219 s]
[INFO] fr.opensagres.xdocreport.remoting.javaclient ....... SUCCESS [  0.265 s]
[INFO] tools .............................................. SUCCESS [  0.016 s]
[INFO] fr.opensagres.xdocreport.openoffice.tools .......... SUCCESS [  1.191 s]
[INFO] fr.opensagres.xdocreport.openoffice.macro .......... SUCCESS [  0.428 s]
[INFO] fr.opensagres.xdocreport.document.docx ............. SUCCESS [  3.128 s]
[INFO] fr.opensagres.xdocreport.document.pptx ............. SUCCESS [  1.302 s]
[INFO] fr.opensagres.xdocreport.document.odt .............. FAILURE [  3.071 s]
[INFO] fr.opensagres.xdocreport.document.ods .............. SUCCESS [  0.266 s]
[INFO] fr.opensagres.xdocreport.document.odp .............. SUCCESS [  0.881 s]
[INFO] fr.opensagres.xdocreport.template.freemarker ....... SUCCESS [  3.769 s]
[INFO] fr.opensagres.xdocreport.template.velocity ......... SUCCESS [  3.680 s]
[INFO] XDocReport Remoting Component ...................... SUCCESS [  0.015 s]
[INFO] fr.opensagres.xdocreport.remoting.resources ........ SUCCESS [  0.407 s]
[INFO] fr.opensagres.xdocreport.remoting.resources.services.server SUCCESS [  0.359 s]
[INFO] fr.opensagres.xdocreport.remoting.resources.services.client SUCCESS [  3.169 s]
[INFO] fr.opensagres.xdocreport.document.tools ............ FAILURE [  8.296 s]
[INFO] fr.opensagres.xdocreport.document.textstyling.wiki . SUCCESS [  0.826 s]
[INFO] fr.opensagres.xdocreport.converter.docx.xwpf ....... SUCCESS [  2.307 s]
[INFO] fr.opensagres.xdocreport.converter.odt.odfdom ...... SUCCESS [  1.724 s]
[INFO] fr.opensagres.xdocreport.converter.docx.docx4j ..... SUCCESS [  2.258 s]
[INFO] fr.opensagres.xdocreport.remoting.shared ........... SUCCESS [  0.187 s]
[INFO] XDocReport Integration Tests ....................... SUCCESS [  0.122 s]
[INFO] fr.opensagres.xdocreport.core.test ................. SUCCESS [ 33.913 s]
[INFO] fr.opensagres.xdocreport.osgi.integrationtests ..... FAILURE [ 11.787 s]
[INFO] fr.opensagres.xdocreport.remoting.ws ............... SUCCESS [  0.188 s]
[INFO] fr.opensagres.xdocreport.remoting.rest ............. SUCCESS [  2.801 s]
[INFO] fr.opensagres.xdocreport.converter.fop ............. SUCCESS [  0.344 s]
[INFO] fr.opensagres.xdocreport.converter.fop.docx ........ SUCCESS [  2.422 s]
[INFO] fr.opensagres.xdocreport.converter.fop.odt ......... SUCCESS [  4.815 s]
[INFO] fr.opensagres.xdocreport.remoting.converter ........ SUCCESS [  0.152 s]
[INFO] fr.opensagres.xdocreport.remoting.converter.server . SUCCESS [  5.097 s]
[INFO] fr.opensagres.xdocreport.remoting.reporting ........ SUCCESS [  0.172 s]
[INFO] fr.opensagres.xdocreport.remoting.reporting.server . SUCCESS [  6.149 s]
[INFO] gae ................................................ SUCCESS [  0.889 s]
[INFO] fr.opensagres.xdocreport.itext.extension-gae ....... SUCCESS [  2.245 s]
[INFO] fr.opensagres.poi.xwpf.converter.core-gae .......... FAILURE [  2.022 s]
[INFO] fr.opensagres.poi.xwpf.converter.pdf-gae ........... FAILURE [  0.016 s]
[INFO] fr.opensagres.odfdom.converter.pdf-gae ............. SUCCESS [  2.471 s]
[INFO] fr.opensagres.poi.xwpf.converter.xhtml-gae ......... FAILURE [  0.016 s]
[INFO] uberjar ............................................ SUCCESS [  0.203 s]
[INFO] xdocreport ......................................... FAILURE [  1.539 s]
[INFO] xdocreport-gae 2.0.3-SNAPSHOT ...................... FAILURE [  0.025 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by kdebski85** [comment]
I added https://github.com/opensagres/xdocreport/pull/506 to:
1. Upgrade to POI 5.2.0 because 5.1.0 has some known vulnerabilities
2. Fix tests. However, tests in "fr.opensagres.xdocreport.osgi.integrationtest" are still failing. I do not use OSGI and I do not know how to fix them.

**Comment by kdebski85** [comment]
I managed to fix integration tests. Please see https://github.com/opensagres/xdocreport/pull/508
With this change, the whole project builds with tests successfully.

**Comment by angelozerr** [comment]
2.0.3 uses now poi 5.2.0
