### ISSUE TITLE
convert with JODConverter

### ISSUE THREAD

**Issue by abdoah77** [opensagres/xdocreport#47]
Hi,
I created MyServlet implements AbstractProcessXDocReportServlet for generate à report with OpenOffice odt ,MyServlet works fine and generates report .odt but I want to convert the file generated  to another format with JODConverter API ,my question is how can I retrieve the file generated by the MyServlet and send it to another servelt or programme so that I use JODConverter API to convert the file 

Thanks.

**Comment by angelozerr** [comment]
Th ebest clean mean to do that is to implement a IConverter with JODConverter and use after converter URL parameter to call your implementation of IConverter.

It should be very cool if you could contribute to XDocReport by implementing this converter.

**Comment by abdoah77** [comment]
So if I can 
thanks

**Comment by angelozerr** [comment]
I close this issue because  it's the same issue than https://github.com/opensagres/xdocreport/issues/152

**Comment by abdoah77** [comment]
OK,but Can you explain to me step by step how to implement a IConverter with JODConverter 3.0 and use it in my application to convert file .docx generated by myservlet extends AbstractProcessXDocReportServlet

Thanks a lot .
