### ISSUE TITLE
Duplicate XHTMLPageBeforeBody with different content

### ISSUE THREAD

**Issue by nvollmar** [opensagres/xdocreport#49]
We have a problem when building our assembly: 
_
[04:00:13]Step 1/1: build and deploy (Simple Build Tool (Scala)) (10m:45s)
[04:09:56][Step 1/1] 1 error was encountered during merge
[04:10:58]
[Step 1/1] (reporting/*:assembly) deduplicate: different file contents found in the following:
/home/tca/work/teamcityagent/temp/ivy2/cache/fr.opensagres.xdocreport/fr.opensagres.xdocreport.itext.extension/jars/fr.opensagres.xdocreport.itext.extension-1.0.5.jar:fr/opensagres/xdocreport/xhtml/extension/XHTMLPageBeforeBody.class
/home/tca/work/teamcityagent/temp/ivy2/cache/fr.opensagres.xdocreport/org.odftoolkit.odfdom.converter.xhtml/jars/org.odftoolkit.odfdom.converter.xhtml-1.0.5.jar:fr/opensagres/xdocreport/xhtml/extension/XHTMLPageBeforeBody.class
[04:10:59][Step 1/1] Step build and deploy (Simple Build Tool (Scala)) failed
_

The only difference in the two files are:
_import org.odftoolkit.odfdom.converter.core.utils.StringUtils;_
vs
_import fr.opensagres.xdocreport.utils.StringUtils;_

**Comment by angelozerr** [comment]
@nvollmar yes it's a mistake I had done when I have started to refactor docx-> xhtml converter with SAX. I would liek to do the same thing for odt -> xhtml (having a SAX capabilities), but no time to do that.

I have removed the classes to avoid this duplication.
