### ISSUE TITLE
How can I add no list data into a Table?

### ISSUE THREAD

**Issue by mattgolem** [opensagres/xdocreport#510]
I use ODT Document and Freemarker.

How can I add non list data (single value) into a Table?

I like to insert simple fields into a table along with the list fields

**Comment by angelozerr** [comment]
If you create an ODT table and you insert a field like `simpleField` and in your data model you set the `simpleField` value, it should work, no?

**Comment by mattgolem** [comment]
I was wrong because I entered the field as listField.
Thanks
