### ISSUE TITLE
Create a table with nested list objects and master fields

### ISSUE THREAD

**Issue by mattgolem** [opensagres/xdocreport#511]
My model is:
```
public class Determ {
	public Short year;
	
	public List<Attachment> attachments = new ArrayList<>();
}

public class Attachment{
	public String fileName;
}
```

I add Determ to metadata with:

```
public void loadMetadata(FieldsMetadata metadata) {
	metadata.load( "determ", Determ.class, false );
}
```

I like to creare a Table in ODT document with determ.year and determ.attachments.fileName (see example.odt)

[example.odt](https://github.com/opensagres/xdocreport/files/7940299/example.odt)

my first example do error.
my second example produces detached rows.

How can I do to obtain a unique table maintaining my model structure that in reality is more complex?

**Comment by ChengangFeng** [comment]
how can you solve this, I have the same question.
