### ISSUE TITLE
Docx to PDF: default font size not handled

### ISSUE THREAD

**Issue by blagae** [opensagres/xdocreport#52]
Depending on the contents of the node w:docDefaults in /word/styles.xml , we get different default font sizes. This is not translated correctly in PDF conversion.

The default structure of the w:docDefaults node is roughly as follows:
```
<w:docDefaults>
    <w:rPrDefault>
        <w:rPr>
            <w:rFonts w:asciiTheme="minorHAnsi" w:eastAsiaTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi" w:cstheme="minorBidi" />
            <w:sz w:val="22" />
            <w:szCs w:val="22" />
            <w:lang w:val="en-US" w:eastAsia="en-US" w:bidi="ar-SA" />
        </w:rPr>
    </w:rPrDefault>
    <w:pPrDefault>
        <w:pPr>
            <w:spacing w:after="160" w:line="259" w:lineRule="auto" />
        </w:pPr>
    </w:pPrDefault>
</w:docDefaults>
```

The problem lies within the node w:rPrDefault. There are 3 possible scenarios:

1. it is present, and contains font size information
In this case, the default font size in MS Word is obviously equal to the specified value

2. it is present, but doesn't contain font size information
In this case, the default font size is set to 10 in MS Word

3. it is absent
In this case, the default font size is set to 11 in MS Word

The problem is that XDocReport has no provisions for the second and third case. Consequently, no font size information is passed to iText, which defaults to 12.

I have found that this applies to Office 365, Office 2013, and Office 2010. 2007 is unconfirmed as of now. I have no idea if this is a bug or a feature. For the record: I haven't found any documents where scenario 3 applies, but I have found an instance of scenario 2 in the wild.

**Comment by angelozerr** [comment]
Any contribution are welcome!
