### ISSUE TITLE
Dynamic Images in Table with Freemarker syntax in DOCX template

### ISSUE THREAD

**Issue by martoncsukas** [opensagres/xdocreport#53]
Hi,

I have implemented a "DOCX-template" to PDF-with-data functionality using xDocReport with Freemarker.

I can create templates in DOCX using Freemarker's syntax, then xDocReport merges it with the actual data from the database to generate a PDF as an output.

This works like a dream, many thanks for it! 

However I have problems with dynamic images in tables. Let's say I have a table with one column and three different images (in three different rows).

I'd like to generate these images in the PDF. In order to do so, this is what I need in the template docx in the first cell of the table (as Word MergeFields):

> @before-row\[#list Table_1 as row]
>(here would come a placeholder image with a bookmark, where the bookmark is the name of the > image component which I'd like to print)
> @after-row[/#list]

However, I think the bookmark should be "row.something", but I cannot add dot (.) in Word as a bookmark. Please find attached picture.
![capture](https://cloud.githubusercontent.com/assets/5966800/8908800/01523eaa-3476-11e5-82c9-0b94b7b97685.PNG)

The Java side looks like this (excerpt):

```java
// load DOCX Template Document by filling FreeMarker Template Engine
InputStream inputStream = new FileInputStream(templateDocFile);
IXDocReport report = XDocReportRegistry.getRegistry().loadReport(inputStream, TemplateEngineKind.Freemarker);

// create context Java model, data map and fields metadata (to manage images)
IContext context = report.createContext();
Map<String, Object> data = new HashMap<String, Object>();
FieldsMetadata metadata = new FieldsMetadata();
List<Map<String, Object>> rows = new ArrayList<Map<String, Object>>();

// looping through the rows of table - we have some variables to make sure it iterates through all the cells of the table - I didn't put all the row-column iterating logic here
for (int rowIndex = 0; rowIndex <= rowNum - 1; rowIndex++) {
   Map<String, Object> row = new HashMap<String, Object>();
          // looping through the columns of table
          for (int x = 0; x <= colNum - 1; x++) {
              FieldsMetadata metadata = new FieldsMetadata();
              metadata.addFieldAsImage(currentElement.getNameOfImage(),    NullImageBehaviour.RemoveImageTemplate);
              IImageProvider image = new ByteArrayImageProvider(currentElement.getValueAsBytes(), true);
             row.put(currentElement.getNameOfImage(), image);
            report.setFieldsMetadata(metadata);

        }
        rows.add(row);
}

// and later on...
context.put(element.getNameOfTable(), rows); // this would be "Table_1" in our example
Options options = Options.getTo(ConverterTypeTo.PDF).via(ConverterTypeVia.XWPF);
report.convert(context, options, baos);
return baos.toByteArray();
```

Is this correct so far? Can you please provide me a working example of dynamic images in tables using DOCX templates with Freemarker syntax?

Some details:
fr.opensagres.xdocreport.core -- 1.0.4
fr.opensagres.xdocreport.document.docx -- 1.0.4
fr.opensagres.xdocreport.template.freemarker -- 1.0.4
fr.opensagres.xdocreport.converter.docx.xwpf -- 1.0.4
org.apache.poi.xwpf.converter.pdf -- 1.0.4
freemarker -- 2.3.23

**Comment by martoncsukas** [comment]
Unfortunately I cannot use  @FieldMetadata( images = { @ImageMetadata( name = "nameofimage" ) } ) annotation, because I don't have a separate model class for row, because row can have several columns (=members). That's why I am using rows as: List<Map<String, Object>> rows.

**Comment by martoncsukas** [comment]
Hi, I've worked it out! Thanks again for this awesome library, amazing job! Please find the solution below:

```java
// load DOCX Template Document by filling FreeMarker Template Engine
InputStream inputStream = new FileInputStream(templateDocFile);
IXDocReport report = XDocReportRegistry.getRegistry().loadReport(inputStream, TemplateEngineKind.Freemarker);

// create context Java model, data map and fields metadata (to manage images)
IContext context = report.createContext();
Map<String, Object> data = new HashMap<String, Object>();
FieldsMetadata metadata = new FieldsMetadata();

List<Map<String, Object>> rows = new ArrayList<Map<String, Object>>();
Integer colNum = formComponentService.getChildrenOfComponent(element.getComponent()).size();
Integer rowNum = children.size() / colNum;
Integer rowSkip = 0;

// looping through the rows of table
for (int rowIndex = 0; rowIndex <= rowNum - 1; rowIndex++) {

  Map<String, Object> row = new HashMap<String, Object>();

  // looping through the columns of table
  for (int x = 0; x <= colNum - 1; x++) {

	Element currentElement = children.get(rowSkip + x);
	String key = children.get(rowSkip + x).getComponent().getName();
	Object value = null;

	// for PHOTO inside a table
	if (currentElement.getComponent().getType().equalsIgnoreCase("Photo"))) {
	  
		metadata.addFieldAsList("rows." + currentElement.getName());
		metadata.addFieldAsImage(currentElement.getName(), "row." + currentElement.getName(), NullImageBehaviour.RemoveImageTemplate);
		report.setFieldsMetadata(metadata);
		
		IImageProvider image = new ByteArrayImageProvider(currentElement.getValueAsBytes(), false);
		row.put(currentElement.getName(), image)

	} 
	
  }

  rows.add(row);
  rowSkip += colNum;
  
}

// and later on...
context.put(element.getNameOfTable(), rows); // this would be "Table_1" in our example
Options options = Options.getTo(ConverterTypeTo.PDF).via(ConverterTypeVia.XWPF);
report.convert(context, options, baos);
return baos.toByteArray();
```

**Comment by angelozerr** [comment]
> Hi, I've worked it out! Thanks again for this awesome library, amazing job! 

Glad you have found a solution and XDocReport can help you. Can we close this issue,

**Comment by martoncsukas** [comment]
Sure, my problem is solved, the issue can be closed. You might want to add this example to your documentation, as dynamic images in dynamic tables using Freemarker and DOCX could be useful for many else in the future.

**Comment by angelozerr** [comment]
> You might want to add this example to your documentation

Yes sure, but we must rewrite doc inside github wiki since we have migrated the google project wiki to github wiki. It's a very long task, no time for the moment to do that -(

**Comment by neophd** [comment]
martoncsukas, plz share your .docx and whole code, I'm having same problem.
