### ISSUE TITLE
Where can I download version 2.0.3 of XDocReport Document Tools?

### ISSUE THREAD

**Issue by alexjcm** [opensagres/xdocreport#535]
I have searched for this file `fr.opensagres.xdocreport.document.tools-2.0.3-distribution.zip` to download in order to use the latest version of the *marco/XDocReport.dotm* file, but I have not been able to find it, where can I download this file?

**Comment by angelozerr** [comment]
You can find macro at https://github.com/opensagres/xdocreport/tree/master/document/fr.opensagres.xdocreport.document.tools/src/main/resources/macro

But to be honnest with you, this macro has never updated since 9 years.
