### ISSUE TITLE
will there be a more "open" solution for converting to PDF?

### ISSUE THREAD

**Issue by mohamnag** [opensagres/xdocreport#54]
I see that currently the only solution for converting to PDF is using iText. As iText has a very bad licensing, I wanted to ask if you plan to provide a more open option based on other libs like PDFBox?

**Comment by angelozerr** [comment]
PDFBox doesn't provide the same features than iText like creating a PDF with Document, Paragraph, Chunk, etc.

If we wish to use PDFBox we must develop the same widget Document, Paragraph, Chunk, etc with PDFBox. No time to do that and I had posted this question to PDFBox forum. See https://mail-archives.apache.org/mod_mbox/pdfbox-users/201110.mbox/%3CCAKOv7Fmh=OAxOwyJX6nWpD=z8MypOZ4Y1GnAhGoRnc9Qnwoadg@mail.gmail.com%3E

But any contribution are welcome!

**Comment by mohamnag** [comment]
thats sad, the iText's license is a very limiting one.

**Comment by angelozerr** [comment]
LGPL license is not enough for you?

**Comment by mohamnag** [comment]
Which version of iText is this lib using? We need to include it in a closed source system who's source code will never be published, and newer iText is using LGPL v3 which prohibits this.

**Comment by angelozerr** [comment]
We have 2 converters based on iText 2.1.7 (LGPL) and iText 5

**Comment by mohamnag** [comment]
that seems much better, thanks I will then take a look into using iText 2.1.7 converter.
