### ISSUE TITLE
Release date of 2.0.4 ?

### ISSUE THREAD

**Issue by wyfrel** [opensagres/xdocreport#540]
Hello, when are you planning a 2.0.4 release ? I've got a bug that seems fixed in the snapshot version.

thx, best regards,

**Comment by angelozerr** [comment]
No plan today, we wait for that we have more issues.

**Comment by wyfrel** [comment]
@angelozerr : Thx for this reply, this bug : https://github.com/opensagres/xdocreport/issues/89 is creating document not correctly merge on our project. it would be great to have a 2.0.4 release, 2.0.3 is already a few month old :-)

**Comment by angelozerr** [comment]
> @angelozerr : Thx for this reply, this bug : https://github.com/opensagres/xdocreport/issues/89 is creating document not correctly merge on our project. it would be great to have a 2.0.4 release, 2.0.3 is already a few month old :-)

Have you a fix for that?

**Comment by wyfrel** [comment]
I’m not sure to understand your question. It’s already fixed in the 2.0.4 milestone and we have perform the following checks :
- 2.0.3 : issue in document génération (in merge fields)
- 2.0.4-snapshot (build locally) : it’s fixed

**Comment by angelozerr** [comment]
> 2.0.4-snapshot (build locally) : it’s fixed

Please skip my comments.

**Comment by angelozerr** [comment]
If I understand correctly your comment [JonathanLach](https://github.com/JonathanLach) you wish too to have a 2.0.4 release which fixes the problem?

**Comment by JonathanLach** [comment]
It would be nice indeed.

**Comment by wyfrel** [comment]
Any update on the release date ?

**Comment by wyfrel** [comment]
@angelozerr : could you tell us if a release could be planned ?

**Comment by angelozerr** [comment]
@pascalleclercq do you think you will have time to do that?

**Comment by pascalleclercq** [comment]
Done @wyfrel @angelozerr
