### ISSUE TITLE
Architecture: using a ODFUtils method in XWPF

### ISSUE THREAD

**Issue by blagae** [opensagres/xdocreport#61]
I'd like to use ODFUtils::getDimensionAsPoint in the XWPF converter core. For my immediate need, I just copy pasted all required methods to XWPFUtils on my dev machine, but I'm fairly certain that will be unacceptable for you guys :-)

So what do I do ?

**Comment by blagae** [comment]
Also, do you have a specific way of handling CSS-like properties ? I want to parse the style of this XML node:

	<w:pict>
		<v:shape id="_x0000_i1025" type="#_x0000_t75" style="width:175.15pt;height:110.7pt">
			<v:imagedata r:id="rId6" o:title="root"/>
		</v:shape>
	</w:pict>

For now, I wrote an ad hoc mini CSS parser (not very stable, I have to say). ODFUtils::getDimensionAsPoint is actually the second step, after this CSS parsing.

**Comment by angelozerr** [comment]
> I just copy pasted all required methods to XWPFUtils on my dev machine

I have though about this problem : having a commons JARs or not for ODT/XWPF converters. I have decided not to have this commons JARs, because it will add a new JARs to use converters and I hope one day we will donate our work on POI and ODFDOM. In other words it's teh correct mean.

> Also, do you have a specific way of handling CSS-like properties ? I want to parse the style of this XML node:

For converter, we have not that (our converter doesn't support style), it's a cool feature! I think it's a good idea to have a simple CSS Parser to avoid having a new dependencies to SAC API and SAC implementation (Flute, Batik).

**Comment by blagae** [comment]
Ok I just pushed a new branch to my own fork with the code I worked on to add support for <w:pict>. It only has one (big) commit so far, which builds correctly. It's very much an incomplete feature with a lot of TODOs and no tests. If you've got any pointers or criticisms, be my guest. It adds an abstract method to the interface of XWPFDocumentVisitor - I did my best to implement it correctly for the XHTMLMapper, but I'm not sure how well it works.

https://github.com/blagae/xdocreport/tree/feature/picture

**Comment by angelozerr** [comment]
Your fork seems not break existing code. Please create a PR and we will adjust it if there are problem. 

Could you please add a new test with your docx please. 

Thanks.

**Comment by angelozerr** [comment]
And is it possible to do the same thing for our converter based on iText 2.1.7 please.

**Comment by blagae** [comment]
I'm still developing some of the features, I'll create a PR when I have a completer and tested solution for this.

I made the same changes in the PdfMapper class in both the iText 2 and iText 5 plugins. I had to, because the new method in XWPFDocumentVisitor is abstract ...

**Comment by blagae** [comment]
Questions were answered, further development is subject to its own PR when it is mature.
