### ISSUE TITLE
Versioning: Upgrade to upcoming iText 5.5.7

### ISSUE THREAD

**Issue by blagae** [opensagres/xdocreport#63]
I looked into building XDocReport with the latest version of iText 5, but it turns out that something changed in iText 5.4.2 that made the AbstractXWPFPOIConverterTest::AdvancedTable2 test in org.apache.poi.xwpf.converter.pdf.itext5 fail with a NullPointerException. I fixed this yesterday in iText with a simple null check, but another very recent commit on iText's develop branch (https://github.com/itext/itextpdf/commit/48b4e460a208c51257121ba877ec8a4bd3c2416f) made another test fail, namely AbstractODFDOMConverterTest::Issue247 in org.odftoolkit.converter.pdf.itext5 .

Turns out that a new overloaded method was added in iText's PdfContentByte which isn't "properly" overridden in XDocReport's ExtendedPdfContentByte (because it can't access that method until iText releases another version). I have fixed that as well in XDocReport, but I can only push that commit after the release of iText 5.5.7 (tentatively scheduled for September 15th). Both fixes aren't in iText 5.5.6, of course, and will both be included in iText 5.5.7

This all means that XDocReport 1.0.5 won't build with any iText version higher than 5.4.1, and any versions of XDocReport after a pull request for this issue won't build with any iText version lower than 5.5.7. I don't have a lot of experience with versioning problems, so I have no idea what to do. Do you have any suggestions ?

**Comment by angelozerr** [comment]
If it's not complex, you could use reflection to support all iText 5 version. I had done that for instance to support JDK 5 and 6 for service loader https://github.com/opensagres/xdocreport/blob/master/core/fr.opensagres.xdocreport.core/src/main/java/fr/opensagres/xdocreport/core/internal/JDKServiceLoader.java

**Comment by blagae** [comment]
I've investigated this, and it's impossible to use reflection because the call to the overridden method addImage() happens in iText itself. There is no way to tell iText to call the other overloaded method from outside, because all parameters come from internal calculations.

Since I need a method that only occurs from iText 5.5.7 on, I need to put that version in the POM file anyway. So I think that it won't pose a problem, because older versions won't compile (this inheritance problem can't be fixed with reflection). Is it all right with you if we just force iText 5 users to go to the newest versions ? I don't see any downsides to that approach, but your opinion may vary.

**Comment by angelozerr** [comment]
> Is it all right with you if we just force iText 5 users to go to the newest versions ? I don't see any downsides to that approach, but your opinion may vary.

I think you are the best guy to take this choice. If you think we should force the converter to use iText 5.5.7, I'm OK. @pascalleclercq what do you think about that?

**Comment by blagae** [comment]
FYI we have decided to move forward with upgrading iText 5.5.7, since we don't know of any users whose workflow would break. And if their workflow breaks and they shout out about it, then at least we would know about it and be able to fix problems they might have :)

Also, we need to make a choice when creating a CompareTool (see #64 ) and it seemed logical to me to use the more modern API.

I will create a pull request when iText 5.5.7 is released.
