### ISSUE TITLE
Publish version with poi 5.2.5 support

### ISSUE THREAD

**Issue by ase379** [opensagres/xdocreport#639]
The version 2.0.4 using poi 5.2.0 has conflicts with the log4j dependencies and the 2.0.5 is not publishe to the maven central.

What can I do to solve this ? Or can anyone publish the 2.0.5 to the central maven repo ?

**Comment by Adriansun** [comment]
Easy upgrade. They should do it.

**Comment by ase379** [comment]
How can I ask them to do so ? I never did that before...

**Comment by Adriansun** [comment]
You just ask here. I am sure they can squeeze it in with the 2.0.5 release. They might not have the most time in the world, but they have the time to up their dependencies and clean, install and test.
