### ISSUE TITLE
document html style

### ISSUE THREAD

**Issue by hungcu** [opensagres/xdocreport#65]
I am working on the project in which fields need to be format as a html style. Are there any ways that we can set the whole docx document with HTML style ? Because the value of the fields are getting from a dynamic xml structure. Therefore, I can not use the FieldsMetadata to handle this.

**Comment by angelozerr** [comment]
Before generating your docx, you could call IXDocReport#extractFields to extract fields. After that you will able to create a FieldsMetadata by using those fields.

Otherwise, I have added a new method `FieldMetadata getFieldAsTextStyling(String content)` https://github.com/opensagres/xdocreport/blob/master/template/fr.opensagres.xdocreport.template/src/main/java/fr/opensagres/xdocreport/template/formatter/FieldsMetadata.java#L363

So to support your feature, you could create extends FieldMetadata and override this method to return every time a FieldMetadata instance. But pay attention of you use #if, #end inside a mergefield, you must return null in this case.

Tell me if it help you.

**Comment by hungcu** [comment]
I have tried the first method and I have run into a weird situation. I created an mergefield <strong>${html.test}</strong> in my document and used the code below:
<strong>FieldsExtractor<FieldExtractor> fieldsExtractor = new FieldsExtractor<>();
report.extractFields(fieldsExtractor);
FieldsMetadata metadata = report.createFieldsMetadata();
List<FieldExtractor> fields = fieldsExtractor.getFields();
for(FieldExtractor field : fields){
            String name = field.getName();
            metadata.addFieldAsTextStyling(name, SyntaxKind.Html );
            context.put(name,"\<strong>test123\</strong>");
}</strong>
The field does not show up as an HTML style format. However, If I change my code to 
<strong>String name = "html.test";
FieldsMetadata metadata = report.createFieldsMetadata();
metadata.addFieldAsTextStyling(name, SyntaxKind.Html );
context.put(name,"\<strong>test123\</strong>");</strong>
then it works. It seems to me that after "fieldsExtractor.getFields()", I can not set fields as SyntaxKind.HTML

**Comment by angelozerr** [comment]
Yes you are right, when extractFields is called it caches the report. So you must read twice the docx:

```java
InputStream in = ...

// 1) Load report without caching to get fields
IXDocReport report1 = XDocReportRegistry.getRegistry().loadReport(in,
		TemplateEngineKind.Velocity, false);
FieldsExtractor<FieldExtractor> extractor = new FieldsExtractor<FieldExtractor>();
report1.extractFields(extractor);

// 2) Load report with cache to generate report
IXDocReport report2 = XDocReportRegistry.getRegistry().loadReport(in,
		TemplateEngineKind.Velocity, false);
IContext context = report2.createContext();
FieldsMetadata metadata = report2.createFieldsMetadata();
List<FieldExtractor> fields = extractor.getFields();
for (FieldExtractor field : fields) {
	String name = field.getName();
	metadata.addFieldAsTextStyling(name, SyntaxKind.Html);
	context.put(name, "<strong>test123</strong>");
}
```

**Comment by hungcu** [comment]
yeah this works perfectly thank you very much :)
However, there is one thing that I want to point out that you cannot read InputStream more than once.

**Comment by angelozerr** [comment]
> However, there is one thing that I want to point out that you cannot read InputStream more than once.

Yes you are right, but to be honnest with you, I have not tested my code. I close this issue.
