### ISSUE TITLE
Create pdf file version 1.7

### ISSUE THREAD

**Issue by bijeshcnair** [opensagres/xdocreport#66]
Im using XDoc api to create pdf file from docx. 

Using api   PdfConverter.getInstance().convert( <document>,<outStream>, <options? );

The pdf document is getting created but its of version 1.4. 
How can I create PDF documents of version 1.7 with this api ?

Thanks in advance 
Bijesh

**Comment by angelozerr** [comment]
Please read https://github.com/opensagres/xdocreport/wiki/XWPFConverterPDFViaIText#ipdfwriterconfiguration and use PdfWriter#setPdfVersion

**Comment by angelozerr** [comment]
@bijeshcnair have you fixed your prblem?

**Comment by bijeshcnair** [comment]
Hi
Yes it has
Thanks for the support

**Comment by angelozerr** [comment]
> Thanks for the support


You are welcome.

I close this issue.
