### ISSUE TITLE
Some Latin Extended-A characters missing while DOCX->PDF conversion

### ISSUE THREAD

**Issue by filippucher** [opensagres/xdocreport#84]
Hello,

I have implemented docx to pdf conversion, running as service on Jboss EAP 6.3 / CentOS 6
Output is pdf file returned from REST service as @Produces("application/pdf")
Data are UTF-8 encoded and every setting is set to UTF-8.
xdocreport version 1.0.5

Problem: some specific characters are not converted, they are missing from the pdf and blank space is inserted instead. These characters come from Latin Extended-A block.

When I change the REST outcome to @Produces("application/msword") and run IXDocReport process instead and get the docx as output then everything is fine.

I tried a lot of things: set up jvm params (user.language, user.country, file.encoding), CentOS locale, in java code called Locale.setDefault, set up xdocreport pdfOptions fontEncoding, but without success.

Missing characters are these and their respective capital letter counterparts:
http://www.fileformat.info/info/unicode/char/010d/index.htm
http://www.fileformat.info/info/unicode/char/010f/index.htm
http://www.fileformat.info/info/unicode/char/013a/index.htm
http://www.fileformat.info/info/unicode/char/013e/index.htm
http://www.fileformat.info/info/unicode/char/0148/index.htm
http://www.fileformat.info/info/unicode/char/0155/index.htm
http://www.fileformat.info/info/unicode/char/0165/index.htm

How to get the correct output?

**Comment by angelozerr** [comment]
Is it working with a simple Java main? Perhaps your server doesn't contains the welll font?

**Comment by filippucher** [comment]
With simple Java main where output goes to FileOutputStream
- at computer running Win7 everything is working fine,
- at CentOS console there is the same problem as with application running on Jboss.

Will try installing fonts. Any other suggestions? Thanks.

**Comment by angelozerr** [comment]
> Will try installing fonts. 

Yes I think it's your problem.

**Comment by filippucher** [comment]
Well done. It works. I've installed DejaVu fonts, changed template document by using these fonts and it works like a charm.

Thanks.

**Comment by filippucher** [comment]
Addendum

I found out something interesting and its workaround.

This works fine, both with simple main and server app, Latin Extended-A characters are well displayed:
```java
import org.odftoolkit.odfdom.converter.pdf.PdfOptions;

PdfOptions pdfOptions = PdfOptions.create().fontEncoding("UTF-8");
Options options = Options.getTo(ConverterTypeTo.PDF).via(ConverterTypeVia.XWPF).subOptions(pdfOptions);
```
But when I use Apache PdfOptions, as I do DOCX to PDF via XWPF conversion, output is not correct. Wide blank space is inserted instead of every Latin Extended-A character.
```java
import org.apache.poi.xwpf.converter.pdf.PdfOptions;
```

**Comment by hedza06** [comment]
@filippucher did you fix the blank spaces. Same happened to me.

**Comment by thanhnv996** [comment]
> 

Can you help me push full code to refer?
