### ISSUE TITLE
The docx to XHTML converters' loggers are configured with the wrong classes

### ISSUE THREAD

**Issue by jrnorth** [opensagres/xdocreport#85]
`Docx2XHTMLViaDocx4jConverter`'s logger is configured with `Docx2PDFViaDocx4jConverter`, and `XWPF2XHTMLConverter`'s logger is configured with `XWPF2PDFViaITextConverter`.

**Comment by angelozerr** [comment]
Is there any chance to have a PR to fix that? Thanks!

**Comment by angelozerr** [comment]
Ooops sorry I have not seen yoru PR https://github.com/opensagres/xdocreport/pull/86 Thanks!
