### ISSUE TITLE
Problem reading Docx files with BOM in xml

### ISSUE THREAD

**Issue by jwatters1981** [opensagres/xdocreport#95]
xdocreport will throw an exception when it tries to load the attached file, this is due to BOM markup in one of the xml files.
A smaill change in the DocReport onBeforePreprocessing method will resolve the issue please see the below.

```
			InputStream stream = preprocessedArchive.getEntryInputStream( relsEntryName );           
			try
            {
   
				SAXParserFactory.newInstance().newSAXParser().parse(stream, contentHandler);
```
instead of 
```
 Reader reader = preprocessedArchive.getEntryReader( relsEntryName );
            try
            {
                XMLReader xmlReader = XMLReaderFactory.createXMLReader();
                xmlReader.setContentHandler( contentHandler );
                xmlReader.parse( new InputSource( reader ) );
```
I'm happy do to a pull request and make this change if its deemed an issue.
[bookmark24.docx](https://github.com/opensagres/xdocreport/files/45735/bookmark24.docx)

**Comment by angelozerr** [comment]
Yes please do a PR please. It will execute travis to check if your change id OK with our JUnit.

Thanks!
